<a href="https://colab.research.google.com/github/SonishMaharjanfuse/Assignment-4-Pandas/blob/dev_pandas_assignment/pandas_basics_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas
<li>Pandas is an open-source Python package that is built on top of NumPy used for working with data sets.</li>
<li>The name "Pandas" has a reference to <b>"Python Data Analysis".</b></li>
<li>Pandas is considered to be one of the best data-wrangling packages.</li>
<li>Pandas offers user-friendly, easy-to-use data structures and analysis tools for analyzing, cleaning, exploring and manipulating data.</li>
<li>It also functions well with various other data science Python modules.</li>

# Difference Between NumPy & Pandas

![](images/pandas_vs_numpy.png)

## Why Use Pandas?

<li>Pandas is known for its exceptional ability to represent and organize data.</li>
<li>The Pandas library was created to be able to work with large datasets faster and more efficiently than any other library.</li>
<li>It excels at analyzing huge amounts of data.Pandas allows us to analyze big data and make conclusions based on statistical theories.</li>
<li>Pandas can clean messy data sets, and make them readable and relevant.</li>
<li>By combining the functionality of Matplotlib and NumPy, Pandas offers users a powerful tool for performing <b>data analytics and visualization.</b></li>
<li>Data can be imported to Pandas from a variety of file formats, such as Csv, SQL, Excel, and JSON, among others.</li>
<li>Pandas is a versatile and marketable skill set for data analysts and data scientists that can gain the attention of employers.</li>

## Installation Of Pandas
<li>Go to your terminal, open and activate your virtual environment and then use the following commands for installing pandas.</li>

<code>
    pip install pandas
</code>

## Importing Pandas
<li>We need to import pandas if we want to create a pandas dataframe and perform any analysis on them.</li>
<li>We can import pandas package using the following command:</li>
<code>
    import pandas as pd
</code>

In [ ]:
import pandas as pd

## How To Create A Pandas DataFrame
<li>A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, arranged in a table like structure with rows and columns.</li>
<li>We can create a basic pandas dataframe by various methods.</li>
<li>Let's discuss some of the methods to create the given dataframes:</li>

![](images/dataframe.png)

### 1. From Python Dictionary

In [ ]:
df1 = pd.DataFrame({'Name': ['Prabhat', 'Hari', 'Shyam',
                             'Sita', 'Mahima', 'Sunil', 'Bhawana'],
                   'Age': [24,34,50,32,18,23,22],
                   'Address': ['Manigram', 'Dhanewa', 'Bardaghat', 'Manglapur',
                              'Bharatpur', 'Kathmandu', 'Ramechap']})

In [ ]:
df1

      Name  Age    Address
0  Prabhat   24   Manigram
1     Hari   34    Dhanewa
2    Shyam   50  Bardaghat
3     Sita   32  Manglapur
4   Mahima   18  Bharatpur
5    Sunil   23  Kathmandu
6  Bhawana   22   Ramechap

### 2. From a list of dictionaries

In [ ]:
df2 = pd.DataFrame([{'Name': 'Prabhat', 'Age': 24, 'Address' : 'Manigram'},
                    {'Name': 'Hari', 'Age': 34, 'Address' : 'Dhanewa'},
                    {'Name': 'Shyam', 'Age': 50, 'Address' : 'Bardaghat'},
                    {'Name': 'Sita', 'Age': 32, 'Address' : 'Manglapur'},
                    {'Name': 'Mahima', 'Age': 18, 'Address' : 'Bharatpur'},
                    {'Name': 'Sunil', 'Age': 23, 'Address' : 'Kathmandu'},
                    {'Name': 'Bhawana', 'Age': 22, 'Address' : 'Ramechap'}
                   ])

In [ ]:
df2

      Name  Age    Address
0  Prabhat   24   Manigram
1     Hari   34    Dhanewa
2    Shyam   50  Bardaghat
3     Sita   32  Manglapur
4   Mahima   18  Bharatpur
5    Sunil   23  Kathmandu
6  Bhawana   22   Ramechap

### 3. From a list of tuples

In [ ]:
df3 = pd.DataFrame([('Prabhat', 24, 'Manigram'),
                    ('Hari', 34, 'Dhanewa'),
                    ('Shyam',50, 'Bardaghat'),
                    ('Sita', 32, 'Manglapur'),
                    ('Mahima', 18, 'Bharatpur'),
                    ('Sunil', 23, 'Kathmandu'),
                    ('Bhawana', 22, 'Ramechap')
                   ], columns = ['Name', 'Age', 'Address'])

In [ ]:
df3

      Name  Age    Address
0  Prabhat   24   Manigram
1     Hari   34    Dhanewa
2    Shyam   50  Bardaghat
3     Sita   32  Manglapur
4   Mahima   18  Bharatpur
5    Sunil   23  Kathmandu
6  Bhawana   22   Ramechap

### 4. From list of lists

In [ ]:
df4 = pd.DataFrame([['Prabhat', 24, 'Manigram'],
                    ['Hari', 34, 'Dhanewa'],
                    ['Shyam',50, 'Bardaghat'],
                    ['Sita', 32, 'Manglapur'],
                    ['Mahima', 18, 'Bharatpur'],
                    ['Sunil', 23, 'Kathmandu'],
                    ['Bhawana', 22, 'Ramechap']
                   ], columns = ['Name', 'Age', 'Address'])

In [ ]:
df4

      Name  Age    Address
0  Prabhat   24   Manigram
1     Hari   34    Dhanewa
2    Shyam   50  Bardaghat
3     Sita   32  Manglapur
4   Mahima   18  Bharatpur
5    Sunil   23  Kathmandu
6  Bhawana   22   Ramechap

#### Question:
<li>Read 'weather_data.csv' file using csv reader.</li>
<li>Store the data inside the csv file into a list of lists.</li>
<li>Then create a pandas dataframe using list of list.</li>

In [ ]:
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (4.6.6)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown) (3.12.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown) (2.31.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from gdown) (1.16.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown) (4.65.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown) (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2023.7.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
!gdown https://drive.google.com/uc?id=1xSh87wC1bFnCnWzgW7ktDQHRL5amnLbH

Downloading...
From: https://drive.google.com/uc?id=1xSh87wC1bFnCnWzgW7ktDQHRL5amnLbH
To: /content/csv_data.zip
100% 2.56M/2.56M [00:00<00:00, 12.4MB/s]

In [ ]:
!unzip csv_data.zip

Archive:  csv_data.zip
replace csv_data/.ipynb_checkpoints/knn-checkpoint.ipynb? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
from csv import reader

file = open('csv_data/weather_data.csv')
file_reader = reader(file)
data = list(file_reader)
print(data)

[['kfjkdfjskd'], ['dfuhsdjufio'], ['day', 'temperature', 'windspeed', 'event'], ['1/1/2017', '32', '6', 'Rain'], ['1/4/2017', 'not available', '9', 'Sunny'], ['1/5/2017', '-1', 'not measured', 'Snow'], ['1/6/2017', 'not available', '7', 'no event'], ['1/7/2017', '32', 'not measured', 'Rain'], ['1/8/2017', 'not available', 'not measured', 'Sunny'], ['1/9/2017', 'not available', 'not measured', 'no event'], ['1/10/2017', '34', '8', 'Cloudy'], ['1/11/2017', '-4', '-1', 'Snow'], ['1/12/2017', '26', '12', 'Sunny'], ['1/13/2017', '12', '12', 'Rainy'], ['1/11/2017', '-1', '12', 'Snow'], ['1/14/2017', '40', '-1', 'Sunny']]

In [ ]:
weather_df = pd.DataFrame(data[3:], columns = data[2])
weather_df

          day    temperature     windspeed     event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

#### Question
<li>1. Read 'imports-85.data' file using file reader.</li>
<li>2. Store the data present inside the file into a list of list.</li>
<li>3. Create a pandas dataframe using list of lists.</li>
<li>4. For column name, we can use the columns variable given below.</li>

In [ ]:
total_data = []
file = open('./csv_data/imports-85.data', 'r')
data_read = file.readlines()
for item in data_read:
    item_list = item.split('\n')[:-1]
    new_item_list = item_list[0].split(',')
    total_data.append(new_item_list)

In [ ]:
columns = ['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration', 'num_of_doors',
          'body_style', 'drive_wheels', 'engine_location', 'wheel_base', 'length', 'width',
           'height', 'curb_weight', 'engine_type', 'num_of_cylinders', 'engine_size', 'fuel_system',
          'bore', 'stroke', 'compression', 'horsepower', 'peak_rpm', 'city_mpg', 'highway_mpg',
           'price']

In [ ]:
df4 = pd.DataFrame(total_data, columns=columns)
df4

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.50,...,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.80,...,109,mpfi,3.19,3.40,10.00,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.40,...,136,mpfi,3.19,3.40,8.00,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,8.70,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.10,...,173,mpfi,3.58,2.87,8.80,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.10,...,145,idi,3.01,3.40,23.00,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.10,...,141,mpfi,3.78,3.15,9.50,114,5400,19,25,22625

### 5. Pandas Dataframe From Csv files

<li>We can load a csv file and create a dataframe out of the data present inside a csv file using pandas.</li>
<li>We have <b>.read_csv()</b> method to read a csv file and create a pandas dataframe from the dataset.</li>

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv', header=2)

In [ ]:
weather_df

          day    temperature     windspeed     event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

### Reading a csv file using skiprows and header parameters

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv',skiprows = 1)

In [ ]:
weather_df

                                     dfuhsdjufio
day       temperature   windspeed          event
1/1/2017  32            6                   Rain
1/4/2017  not available 9                  Sunny
1/5/2017  -1            not measured        Snow
1/6/2017  not available 7               no event
1/7/2017  32            not measured        Rain
1/8/2017  not available not measured       Sunny
1/9/2017  not available not measured    no event
1/10/2017 34            8                 Cloudy
1/11/2017 -4            -1                  Snow
1/12/2017 26            12                 Sunny
1/13/2017 12            12                 Rainy
1/11/2017 -1            12                  Snow
1/14/2017 40            -1                 Sunny

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv', header = 2)
weather_df

          day    temperature     windspeed     event
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

#### Reading a csv file without header and giving names to the columns

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv',skiprows = 3, header = None,
                        names = ['dates', 'temp', 'ws', 'forecast'])
weather_df

        dates           temp            ws  forecast
0    1/1/2017             32             6      Rain
1    1/4/2017  not available             9     Sunny
2    1/5/2017             -1  not measured      Snow
3    1/6/2017  not available             7  no event
4    1/7/2017             32  not measured      Rain
5    1/8/2017  not available  not measured     Sunny
6    1/9/2017  not available  not measured  no event
7   1/10/2017             34             8    Cloudy
8   1/11/2017             -4            -1      Snow
9   1/12/2017             26            12     Sunny
10  1/13/2017             12            12     Rainy
11  1/11/2017             -1            12      Snow
12  1/14/2017             40            -1     Sunny

#### Read limited data from a csv file using nrows parameters

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv',skiprows = 3,nrows = 5, header = None,
                        names = ['dates', 'temp', 'ws', 'forecast'])
weather_df

      dates           temp            ws  forecast
0  1/1/2017             32             6      Rain
1  1/4/2017  not available             9     Sunny
2  1/5/2017             -1  not measured      Snow
3  1/6/2017  not available             7  no event
4  1/7/2017             32  not measured      Rain

#### Reading csv files with na_values parameters ('weather_data.csv' file)

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv',skiprows = 2,
                        na_values = ['not available', 'not measured',
                                    'no event']
                        )
weather_df

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0       -1.0    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0       -1.0   Sunny

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv',skiprows = 2,
                        na_values = {'temperature': 'not available',
                                     'windspeed': ['not measured', -1],
                                    'event': 'no event'})
weather_df

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0        NaN    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0        NaN   Sunny

#### Write a pandas dataframe to a csv file
<li>We can write a pandas dataframe to a csv file using .to_csv() method.</li>
<li>You can specify any name to the csv file while writing a pandas dataframe into a csv file.</li>

In [ ]:
weather_df.to_csv('weather_data_nan.csv', index = False)

### 6. Pandas Dataframe From Xcel files

<li>We can load an excel file with <b>.xlsx</b> extension and create a dataframe out of the data present inside an excel file using pandas.</li>
<li>We have <b>.read_excel()</b> method to read a csv file and create a pandas dataframe from the dataset.</li>
<li>We also need to install <b>openpyxl</b> for working with excel files.</li>

In [ ]:
weather_df = pd.read_excel('./csv_data/weather_data.xlsx',
                           na_values = {'temperature': 'not available',
                                     'windspeed': ['not measured', -1],
                                    'event': 'no event'})
weather_df

    Unnamed: 0        day  temperature  windspeed   event
0            0   1/1/2017         32.0        6.0    Rain
1            1   1/4/2017          NaN        9.0   Sunny
2            2   1/5/2017         -1.0        NaN    Snow
3            3   1/6/2017          NaN        7.0     NaN
4            4   1/7/2017         32.0        NaN    Rain
5            5   1/8/2017          NaN        NaN   Sunny
6            6   1/9/2017          NaN        NaN     NaN
7            7  1/10/2017         34.0        8.0  Cloudy
8            8  1/11/2017         -4.0        NaN    Snow
9            9  1/12/2017         26.0       12.0   Sunny
10          10  1/13/2017         12.0       12.0   Rainy
11          11  1/11/2017         -1.0       12.0    Snow
12          12  1/14/2017         40.0        NaN   Sunny

#### Writing to an excel file
<li>We can write a pandas dataframe into a excel file using .to_excel() method.</li>

In [ ]:
weather_df.to_excel('weather_data.xlsx', 'nans')

#### Using head() and tail() method to see top 5 and last 5 rows
<li>To view the first few rows of our dataframe, we can use the DataFrame.head() method.</li>
<li>By default, it returns the first five rows of our dataframe.</li>
<li>However, it also accepts an optional integer parameter, which specifies the number of rows.</li>

<li>Similarly, to view the last few rows of our dataframe, we can use the DataFrame.tail() method.</li>
<li>By default, it returns the last five rows of our dataframe.</li>
<li>However, it also accepts an optional integer parameter, which specifies the number of rows.</li>

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data.csv', skiprows = 2)
weather_df.head(3)

In [ ]:
weather_df.tail(3)

#### Question:

<li>Use the head() method to select the first 6 rows.</li>
<li>Use the tail() method to select the last 8 rows.</li>

In [ ]:
weather_df.head(6)

In [ ]:
weather_df.tail(8)

#### Finding the column names from the dataframe
<li>We have df.columns attributes to check the name of columns in the pandas dataframe.</li>
<li>Similarly, we have df.values attributes to check the data present in the pandas dataframe.</li>

In [ ]:
weather_df.columns

In [ ]:
print(type(weather_df.columns))

In [ ]:
weather_df.columns[-2:]

In [ ]:
list(weather_df.columns)[:2]

In [ ]:
weather_df.values

In [ ]:
type(weather_df.values)

In [ ]:
weather_df.values.shape

In [ ]:
weather_df.values.ndim

In [ ]:
weather_df.size

In [ ]:
weather_df.values[-5:]

In [ ]:
weather_df.values[weather_df.values[:,-1] == 'Sunny']

In [ ]:
weather_df.values[weather_df.values[:,1] == 'not available']

In [ ]:
weather_df.values[weather_df.values[:,2] == 'not measured']

In [ ]:
weather_df.values[weather_df.values[:,-1] == 'no event']

#### Checking the type of your dataframe
<li>Another feature that makes pandas better for working with data is that dataframes can contain more than one data type.</li>
<li>Axis values can have string labels, not just numeric ones.</li>
<li>Dataframes can contain columns with multiple data types: including integer, float, and string.</li>
<li>We can use the DataFrame.dtypes attribute (similar to NumPy) to return information about the types of each column.</li>
<li>When we import data, pandas attempts to guess the correct dtype for each column.</li>
<li>Generally, pandas does well with this, which means we don't need to worry about specifying dtypes every time we start to work with data.</li>

In [ ]:
weather_df.dtypes

In [ ]:
weather_df_nan = pd.read_csv('weather_data_nan.csv')
weather_df_nan.head()

In [ ]:
weather_df_nan.dtypes

#### Datatypes Information
<li>We can get the shape of the dataset using <b>.shape()</b> method.</li>
<li><b>.shape()</b> method returns the tuple datatype containing the number of rows and number of columns in the dataset.</li>
<li>If we wanted an overview of all the dtypes used in our dataframe, we can use <b>.info()</b> method.</li>
<li>Note that <b>DataFrame.info()</b> prints the information, rather than returning it, so we can't assign it to a variable.</li>

In [ ]:
weather_df_nan.shape

In [ ]:
weather_df_nan.info()

#### Checking the null values in the pandas dataframe

In [ ]:
weather_df_nan.isnull().sum()

#### set_index() and reset_index() method

In [ ]:
weather_df_nan = pd.read_csv('weather_data_nan.csv',
                             parse_dates = ['day'])
weather_df_nan.head()

In [ ]:
weather_df_nan.set_index('day', inplace = True)
weather_df_nan

In [ ]:
weather_df_nan.reset_index(inplace = True)
weather_df_nan

In [ ]:
temperature_index_df = weather_df_nan.set_index('temperature')
temperature_index_df.head()

In [ ]:
temperature_reset_index_df = temperature_index_df.reset_index(drop = True)

In [ ]:
temperature_reset_index_df.reset_index(inplace = True)
temperature_reset_index_df

    index        day  windspeed   event
0       0 2017-01-01        6.0    Rain
1       1 2017-01-04        9.0   Sunny
2       2 2017-01-05        NaN    Snow
3       3 2017-01-06        7.0     NaN
4       4 2017-01-07        NaN    Rain
5       5 2017-01-08        NaN   Sunny
6       6 2017-01-09        NaN     NaN
7       7 2017-01-10        8.0  Cloudy
8       8 2017-01-11        NaN    Snow
9       9 2017-01-12       12.0   Sunny
10     10 2017-01-13       12.0   Rainy
11     11 2017-01-11       12.0    Snow
12     12 2017-01-14        NaN   Sunny

In [ ]:
temperature_reset_index_df.reset_index(inplace = True, drop = True)
temperature_reset_index_df

    index        day  windspeed   event
0       0 2017-01-01        6.0    Rain
1       1 2017-01-04        9.0   Sunny
2       2 2017-01-05        NaN    Snow
3       3 2017-01-06        7.0     NaN
4       4 2017-01-07        NaN    Rain
5       5 2017-01-08        NaN   Sunny
6       6 2017-01-09        NaN     NaN
7       7 2017-01-10        8.0  Cloudy
8       8 2017-01-11        NaN    Snow
9       9 2017-01-12       12.0   Sunny
10     10 2017-01-13       12.0   Rainy
11     11 2017-01-11       12.0    Snow
12     12 2017-01-14        NaN   Sunny

#### Selecting a column from a pandas DataFrame

<li>Since our axis in pandas have labels, we can select data using those labels.</li>
<li>Unlike in NumPy, we donot need to know the exact index location of a pandas dataframe.</li>
<li>To do this, we can use the DataFrame.loc[] attribute. The syntax for DataFrame.loc[] is:</li>
<code>
df.loc[row_label, column_label]
</code>

<li>We can use the following shortcut to select a single column:</li>
<code>
df["column_name"]
</code>

<li>This style of selecting columns is very common.</li>

In [ ]:
import pandas as pd
weather_df = pd.read_csv('weather_data_nan.csv')
weather_df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         -1.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

In [ ]:
weather_df.loc[:, 'event']

0       Rain
1      Sunny
2       Snow
3        NaN
4       Rain
5      Sunny
6        NaN
7     Cloudy
8       Snow
9      Sunny
10     Rainy
11      Snow
12     Sunny
Name: event, dtype: object

In [ ]:
weather_df['temperature']

0     32.0
1      NaN
2     -1.0
3      NaN
4     32.0
5      NaN
6      NaN
7     34.0
8     -4.0
9     26.0
10    12.0
11    -1.0
12    40.0
Name: temperature, dtype: float64

#### Questions

<li>Read <b>'appointment_schedule.csv'</b> file using pandas.</li>
<li>Select the <b>'name'</b> column from the given dataset and store to <b>'appointment_names'</b> variable.</li>
<li>Use Python's <b>type()</b> function to assign the type of name column to <b>name_type</b>.</li>

In [ ]:
appointment_df = pd.read_csv('./csv_data/appointment_schedule.csv')
appointment_df.tail()

,name,appointment_made_date,app_start_date,app_end_date,visitee_namelast,visitee_namefirst,meeting_room,description
580,Ryan J. Morgan,2015-01-09T00:00:00,1/16/15 10:00,1/16/15 23:59,NaN,potus,west wing,military honor guard
581,Alexander V. Nevsky,2015-01-09T00:00:00,1/16/15 10:00,1/16/15 23:59,NaN,potus,west wing,military honor guard
582,Montana J. Johnson,2015-01-09T00:00:00,1/16/15 10:00,1/16/15 23:59,NaN,potus,west wing,military honor guard
583,Joseph A. Pritchard,2015-01-09T00:00:00,1/16/15 10:00,1/16/15 23:59,NaN,potus,west wing,military honor guard
584,Martin O. Reina,2015-01-09T00:00:00,1/16/15 10:00,1/16/15 23:59,NaN,potus,west wing,military honor guard

In [ ]:
appointment_df.columns

Index(['name', 'appointment_made_date', 'app_start_date', 'app_end_date',
       'visitee_namelast', 'visitee_namefirst', 'meeting_room', 'description'],
      dtype='object')

In [ ]:
appointment_names = appointment_df.loc[:,'name']
print(appointment_names)

0        Joshua T. Blanton
1          Jack T. Gutting
2        Bradley T. Guiles
3           Loryn F. Grieb
4         Travis D. Gordon
              ...
580         Ryan J. Morgan
581    Alexander V. Nevsky
582     Montana J. Johnson
583    Joseph A. Pritchard
584        Martin O. Reina
Name: name, Length: 585, dtype: object

In [ ]:
appointment_names = appointment_df['name']
print(appointment_names)

0        Joshua T. Blanton
1          Jack T. Gutting
2        Bradley T. Guiles
3           Loryn F. Grieb
4         Travis D. Gordon
              ...
580         Ryan J. Morgan
581    Alexander V. Nevsky
582     Montana J. Johnson
583    Joseph A. Pritchard
584        Martin O. Reina
Name: name, Length: 585, dtype: object

In [ ]:
print(type(appointment_names))

<class 'pandas.core.series.Series'>

In [ ]:
appointment_names.shape

(585,)

#### Pandas Series
<li>Series is the pandas type for one-dimensional objects.</li>
<li>Anytime you see a 1D pandas object, it will be a series. Anytime you see a 2D pandas object, it will be a dataframe.</li>
<li>A dataframe is a collection of series objects, which is similar to how pandas stores the data behind the scenes.</li>

#### Adding a column in a pandas dataframe

In [ ]:
import numpy as np
weather_df['is_play'] = np.nan
print(weather_df.shape)
weather_df.head()

(13, 5)

        day  temperature  windspeed  event  is_play
0  1/1/2017         32.0        6.0   Rain      NaN
1  1/4/2017          NaN        9.0  Sunny      NaN
2  1/5/2017         -1.0        NaN   Snow      NaN
3  1/6/2017          NaN        7.0    NaN      NaN
4  1/7/2017         32.0        NaN   Rain      NaN

In [ ]:
is_play = weather_df['is_play']
print(type(is_play))

<class 'pandas.core.series.Series'>

In [ ]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          13 non-null     object
 1   temperature  9 non-null      float64
 2   windspeed    7 non-null      float64
 3   event        11 non-null     object
 4   is_play      0 non-null      float64
dtypes: float64(3), object(2)
memory usage: 648.0+ bytes

### Selecting Multiple Columns From the DataFrame

![](images/selecting_columns.png)

<li>We can select multiple columns from the dataframe by using the following codes:</li>
<code>
    df.loc[:, ["col1", "col2"]]
</code>

<li>We can use syntax shortcuts for selecting multiple columns by using the following syntax:</li>
<code>
    df[["col1", "col2"]]
</code>

In [ ]:
weather_df = pd.read_csv('weather_data_nan.csv', parse_dates = ['day'])
weather_df.head()

         day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-04          NaN        9.0  Sunny
2 2017-01-05         -1.0        NaN   Snow
3 2017-01-06          NaN        7.0    NaN
4 2017-01-07         32.0        NaN   Rain

In [ ]:
weather_df.set_index('day', inplace = True)

In [ ]:
weather_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         -1.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         -4.0        NaN    Snow
2017-01-12         26.0       12.0   Sunny
2017-01-13         12.0       12.0   Rainy
2017-01-11         -1.0       12.0    Snow
2017-01-14         40.0        NaN   Sunny

In [ ]:
weather_df.loc[:, ["temperature", "event"]].head()

            temperature  event
day
2017-01-01         32.0   Rain
2017-01-04          NaN  Sunny
2017-01-05         -1.0   Snow
2017-01-06          NaN    NaN
2017-01-07         32.0   Rain

In [ ]:
weather_df[['temperature', 'event']].head()

            temperature  event
day
2017-01-01         32.0   Rain
2017-01-04          NaN  Sunny
2017-01-05         -1.0   Snow
2017-01-06          NaN    NaN
2017-01-07         32.0   Rain

In [ ]:
weather_df_no_windspeed = weather_df.drop('windspeed', axis = 1)
weather_df_no_windspeed.head()

            temperature  event
day
2017-01-01         32.0   Rain
2017-01-04          NaN  Sunny
2017-01-05         -1.0   Snow
2017-01-06          NaN    NaN
2017-01-07         32.0   Rain

#### Question:
<li>Read 'car_details.csv' file and create a pandas dataframe from it.</li>
<li>Then only select <b>'name'</b>, <b>'selling price'</b> and <b>'km_driven'</b> columns from the dataframe.</li>

![](images/selecting_3_cols.png)

In [ ]:
car_details_df = pd.read_csv('./csv_data/car_details.csv')
car_details_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
car_details_df.loc[:, ['name', 'selling_price', 'km_driven']].head()

                       name  selling_price  km_driven
0             Maruti 800 AC          60000      70000
1  Maruti Wagon R LXI Minor         135000      50000
2      Hyundai Verna 1.6 SX         600000     100000
3    Datsun RediGO T Option         250000      46000
4     Honda Amaze VX i-DTEC         450000     141000

In [ ]:
car_details_df[['name', 'selling_price', 'km_driven']].head()

                       name  selling_price  km_driven
0             Maruti 800 AC          60000      70000
1  Maruti Wagon R LXI Minor         135000      50000
2      Hyundai Verna 1.6 SX         600000     100000
3    Datsun RediGO T Option         250000      46000
4     Honda Amaze VX i-DTEC         450000     141000

In [ ]:
car_details_limited = car_details_df.drop(['year', 'fuel', 'seller_type',
                                          'transmission', 'owner'],
                                          axis = 1)
car_details_limited.head()

                       name  selling_price  km_driven
0             Maruti 800 AC          60000      70000
1  Maruti Wagon R LXI Minor         135000      50000
2      Hyundai Verna 1.6 SX         600000     100000
3    Datsun RediGO T Option         250000      46000
4     Honda Amaze VX i-DTEC         450000     141000

#### Selecting Rows From A Pandas DataFrame

<li>Now that we've learned how to select columns by label, let's learn how to select rows using the labels of the index axis.</li>
<li>We can use the same syntax to select rows from a dataframe as we do for columns:</li>
<code>
    df.loc[row_label, column_label]
</code>

![](images/selecting_one_row.png)

In [ ]:
weather_df.loc['2017-01-01']

temperature    32.0
windspeed       6.0
event          Rain
Name: 2017-01-01 00:00:00, dtype: object

In [ ]:
weather_df.reset_index(inplace = True)
weather_df.head()

         day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-04          NaN        9.0  Sunny
2 2017-01-05         -1.0        NaN   Snow
3 2017-01-06          NaN        7.0    NaN
4 2017-01-07         32.0        NaN   Rain

In [ ]:
weather_df.set_index('temperature', inplace = True)
weather_df.head()

                   day  windspeed  event
temperature
 32.0       2017-01-01        6.0   Rain
 NaN        2017-01-04        9.0  Sunny
-1.0        2017-01-05        NaN   Snow
 NaN        2017-01-06        7.0    NaN
 32.0       2017-01-07        NaN   Rain

In [ ]:
weather_df.loc[-1]

                   day  windspeed event
temperature
-1.0        2017-01-05        NaN  Snow
-1.0        2017-01-11       12.0  Snow

In [ ]:
weather_df.reset_index(inplace = True)
weather_df.head()

   temperature        day  windspeed  event
0         32.0 2017-01-01        6.0   Rain
1          NaN 2017-01-04        9.0  Sunny
2         -1.0 2017-01-05        NaN   Snow
3          NaN 2017-01-06        7.0    NaN
4         32.0 2017-01-07        NaN   Rain

In [ ]:
weather_df.set_index('event', inplace = True)
weather_df.head()

       temperature        day  windspeed
event
Rain          32.0 2017-01-01        6.0
Sunny          NaN 2017-01-04        9.0
Snow          -1.0 2017-01-05        NaN
NaN            NaN 2017-01-06        7.0
Rain          32.0 2017-01-07        NaN

In [ ]:
weather_df.loc["Sunny"]

       temperature        day  windspeed
event
Sunny          NaN 2017-01-04        9.0
Sunny          NaN 2017-01-08        NaN
Sunny         26.0 2017-01-12       12.0
Sunny         40.0 2017-01-14        NaN

### Selecting Multiple Rows From the DataFrame

![](images/selecting_multiple_rows.png)

In [ ]:
weather_df = weather_df.reset_index().set_index('day')
weather_df.head()

            event  temperature  windspeed
day
2017-01-01   Rain         32.0        6.0
2017-01-04  Sunny          NaN        9.0
2017-01-05   Snow         -1.0        NaN
2017-01-06    NaN          NaN        7.0
2017-01-07   Rain         32.0        NaN

In [ ]:
weather_df.loc[['2017-01-01', '2017-01-04']]

            event  temperature  windspeed
day
2017-01-01   Rain         32.0        6.0
2017-01-04  Sunny          NaN        9.0

#### Indexing & Slicing In Pandas DataFrame

<li>We can slice a dataset from their rows as well as columns.</li>
<li>If we have (5,5) shape data and we want first three rows and first three columns then we need to slice both rows and columns to get a desired shape.</li>
<li>We have df.iloc() method which we can use to do indexing as well as slicing in a dataframe.</li>
<li>Let's practice .iloc() method.</li>

In [ ]:
weather_df.reset_index(inplace = True)

In [ ]:
weather_df[3:6]

         day  event  temperature  windspeed
3 2017-01-06    NaN          NaN        7.0
4 2017-01-07   Rain         32.0        NaN
5 2017-01-08  Sunny          NaN        NaN

In [ ]:
weather_df.iloc[2:5, :2]

         day event
2 2017-01-05  Snow
3 2017-01-06   NaN
4 2017-01-07  Rain

In [ ]:
weather_df.iloc[:,:3]

          day   event  temperature
0  2017-01-01    Rain         32.0
1  2017-01-04   Sunny          NaN
2  2017-01-05    Snow         -1.0
3  2017-01-06     NaN          NaN
4  2017-01-07    Rain         32.0
5  2017-01-08   Sunny          NaN
6  2017-01-09     NaN          NaN
7  2017-01-10  Cloudy         34.0
8  2017-01-11    Snow         -4.0
9  2017-01-12   Sunny         26.0
10 2017-01-13   Rainy         12.0
11 2017-01-11    Snow         -1.0
12 2017-01-14   Sunny         40.0

In [ ]:
weather_df.iloc[11,1]

'Snow'

#### Datatype Conversion In Pandas

<li>Pandas astype() is the one of the most important methods. It is used to change data type of a series.</li>
<li>When a pandas dataframe is created from a csv file,the data type is set automatically.</li>
<li>The datatype will not be what it actually should be at times and this is where we can use astype()  to get desired datatype.</li>
<li>For example, a salary column could be imported as string but to do operations we have to convert it into float.</li>
<li>astype() is used to do such data type conversions.</li>

In [ ]:
weather_df.dtypes

day            datetime64[ns]
event                  object
temperature           float64
windspeed             float64
dtype: object

In [ ]:
weather_df['day'] = weather_df['day'].astype('str')

In [ ]:
weather_df.dtypes

day             object
event           object
temperature    float64
windspeed      float64
dtype: object

In [ ]:
car_details_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
car_details_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [ ]:
import pandas as pd
car_df = pd.read_csv('./csv_data/car_details.csv')
car_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:

car_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [ ]:
car_df[['selling_price', 'km_driven']] = car_df[['selling_price', 'km_driven']].astype('float64')

In [ ]:
car_df.info()

In [ ]:
car_df.head()

#### Value Counts Method

<li>Since series and dataframes are two distinct objects, they have their own unique methods.</li>

<li>Let's look at an example of a series method - the Series.value_counts() method.</li>

<li>This method displays each unique non-null value in a column and their counts in order.</li>

<li>value_counts() is a series only method, we get the following error if we try to use it for dataframes:</li>

<code>
    AttributeError: 'DataFrame' object has no attribute 'value_counts'
</code>

In [ ]:
weather_df = pd.read_csv('weather_data_nan.csv')
weather_df.head()

In [ ]:
weather_df['event'].value_counts()

In [ ]:
weather_df['windspeed'].value_counts()

In [ ]:
car_df = pd.read_csv('./csv_data/car_details.csv')
car_df.head()

In [ ]:
car_df['name'].value_counts()

In [ ]:
car_df['fuel'].value_counts()

#### Creating a frequency table from value_counts

In [ ]:
fuel_count_df = car_df['fuel'].value_counts().to_frame()
fuel_count_df.head()

In [ ]:
fuel_count_df.loc['Diesel']

In [ ]:
fuel_count_df.reset_index(inplace = True)
fuel_count_df.head()

#### Renaming the column names in a pandas dataframe

In [ ]:
fuel_count_df.columns = ['fuel', 'frequency']
fuel_count_df.head()

In [ ]:
fuel_count_df.rename({'fuel': 'fuel_type', 'frequency': 'freq'},
                     inplace = True, axis = 1)
fuel_count_df.head()

In [ ]:
def freq_count_df(df, exist_col, renamed_cols):
    """
    df -> dataframe (dataframe object),
    exist_col -> any feature from the dataframe (string)
    renamed_cols -> name of columns you want to rename with (list)
    """

    freq_count_df = df[exist_col].value_counts().to_frame().reset_index()
    freq_count_df.columns = renamed_cols
    return freq_count_df

In [ ]:
car_df[["seller_type", "transmission", "owner"]]

In [ ]:
seller_type_count_df = freq_count_df(df = car_df,
                                     exist_col = 'seller_type',
                                     renamed_cols = ['seller_type', 'freq']
                                    )
seller_type_count_df.head()

In [ ]:
transmission_count_df = freq_count_df(df = car_df,
                                     exist_col = 'transmission',
                                     renamed_cols = ['transmission', 'freq']
                                    )
transmission_count_df.head()

In [ ]:
owner_count_df = freq_count_df(df = car_df,
                                     exist_col = 'owner',
                                     renamed_cols = ['owner', 'freq']
                                    )
owner_count_df.head()

#### Selecting Items From A Series Method

<li>As with dataframes, we can use Series.loc[] to select items from a series using single labels, a list, or a slice object.</li>
<li>We can also omit loc[] and use bracket shortcuts for all three:</li>

![](images/selecting_series.png)

In [ ]:
fuel_count_series = car_df['fuel'].value_counts()
fuel_count_series.head()

In [ ]:
fuel_count_series.loc['Diesel']

In [ ]:
fuel_count_series.loc[['Diesel', 'Petrol']]

In [ ]:
fuel_count_series.loc["Diesel": "CNG"]

#### Question

<li>Use the value counts method to check the frequency count of different names from 'appointment_schedule.csv' file.</li>
<li>Select only first row from the series.</li>
<li>Select the first row and the last row from the series.</li>
<li>Select the first five rows and the last five rows from the series.</li>

In [ ]:
appointment_df = pd.read_csv('./csv_data/appointment_schedule.csv')
appointment_df.tail()

In [ ]:
name_count_series = appointment_df['name'].value_counts()

In [ ]:
name_count_series.loc["Joshua T. Blanton"]

In [ ]:
name_count_series.loc[["Joshua T. Blanton", "Martin O. Reina"]]

#### DataFrame Vs DataSeries

![](images/dataframe_vs_series.png)

#### Summary

![](images/pandas_selection_summary.png)

#### Vecotrized Operations In Pandas

<li>We'll explore how pandas uses many of the concepts we learned in the NumPy.</li>
<li>Because pandas is designed to operate like NumPy, a lot of concepts and methods from Numpy are supported.</li>
<li>Recall that one of the ways NumPy makes working with data easier is with vectorized operations.</li>
<li>Just like with NumPy, we can use any of the standard Python numeric operators with series, including:</li>
<code>
    series_a + series_b - Addition
    series_a - series_b - Subtraction
    series_a * series_b - Multiplication
    series_a / series_b - Division
</code>

In [ ]:
car_df['sp_per_kmdriven'] = car_df['selling_price'] / car_df['km_driven']

In [ ]:
car_df['metres_driven'] = car_df['km_driven'] * 1000

In [ ]:
car_df['age_in_years'] = 2023 - car_df['year']

In [ ]:
car_df.head()

In [ ]:
weather_df.head()

In [ ]:
weather_df['temp_in_kelvin'] = 273 + weather_df['temperature']
weather_df.head()

#### Some Statistical Functions In Pandas

<li>Like NumPy, Pandas supports many descriptive stats methods such as mean, median, mode, min, max and so on.</li>
<li>Here are a few of the most useful ones.</li>
<code>
Series.max()
Series.min()
Series.mean()
Series.median()
Series.mode()
Series.sum()
</code>
<li>We can calculate the average value of a particular column(series) using df.column_name.mean().</li>
<li>For calculating the minimum value in a particular column(series), we can use df.column_name.min().</li>
<li>Similarly, for calculating the maximum value in a particular column(series), we can use df.column_name.max().</li>

In [ ]:
car_df['selling_price'].min()

In [ ]:
car_df['selling_price'].max()

In [ ]:
car_df['selling_price'].mean()

In [ ]:
car_df['selling_price'].median()

In [ ]:
car_df['selling_price'].sum()

In [ ]:
car_df['selling_price'].std()

In [ ]:
car_df['owner'].mode()

In [ ]:
car_df['owner'].value_counts()

#### Finding the descriptive statistics of the dataframe using .describe() method

<li>Descriptive statistics include those that summarize the central tendency, dispersion and shape of a dataset's distribution, excluding NaN values.</li>
<li>describe() method in Pandas is used to compute descriptive statistics for all of your numeric columns.</li>
<li>Analyzes both numeric and object series, as well as DataFrame column sets of mixed data types.</li>
<li>The output will vary depending on what is provided.</li>
<li>If we want to see the descriptive statistics of an object datatype then we have to specify <b>df.describe(include = "O")</b></li>

In [ ]:
car_df.describe()

In [ ]:
car_df.describe(include = "O")

#### Assigning Values With Pandas

<li>Just like in NumPy, the same techniques that we use to select data could be used for assignment.</li>

<li>When we selected a whole column by label and used assignment, we assigned the value to every item in that column.</li>

<li>By providing labels for both axes, we can assign them to a single value within our dataframe.</li>

<code>
    df.loc[row_label, col_label] = assignment_value
</code>

In [ ]:
import pandas as pd

In [ ]:
weather_df = pd.read_csv('weather_data_nan.csv')
weather_df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         -1.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

In [ ]:
weather_df.loc[1,'temperature'] = 31

In [ ]:
weather_df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017         31.0        9.0  Sunny
2  1/5/2017         -1.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

In [ ]:
weather_df.loc[3,["temperature", "event"]] = [30, "Sunny"]

In [ ]:
weather_df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017         31.0        9.0  Sunny
2  1/5/2017         -1.0        NaN   Snow
3  1/6/2017         30.0        7.0  Sunny
4  1/7/2017         32.0        NaN   Rain

In [ ]:
weather_df = weather_df.set_index('day')
weather_df.head()

          temperature  windspeed  event
day
1/1/2017         32.0        6.0   Rain
1/4/2017         31.0        9.0  Sunny
1/5/2017         -1.0        NaN   Snow
1/6/2017         30.0        7.0  Sunny
1/7/2017         32.0        NaN   Rain

In [ ]:
weather_df.loc['1/5/2017', 'windspeed'] = 8

In [ ]:
weather_df.head()

          temperature  windspeed  event
day
1/1/2017         32.0        6.0   Rain
1/4/2017         31.0        9.0  Sunny
1/5/2017         -1.0        8.0   Snow
1/6/2017         30.0        7.0  Sunny
1/7/2017         32.0        NaN   Rain

#### Using Boolean Indexing With Pandas Objects (Selection With Condition In Pandas)
<li>We can assign a value by using row label and column label in pandas.</li>
<li>But what if we need to assign a same value to a group of similar rows with the same criteria.</li>
<li> Instead, we can use boolean indexing to change all rows that meet the same criteria, just like we did with NumPy.</li>


<ol>
    <li>Equals: df['series'] == value</li>
    <li>Not Equals: df['series'] != value</li>
    <li>Less than: df['series'] < value</li>
    <li>Less than or equal to: df['series'] <= value</li>
    <li>Greater than: df['series'] > value</li>
    <li>Greater than or equal to: df['series'] >= value</li>
</ol>
<li>These conditions can be used in several ways, most commonly inside .loc to select values with conditions.</li>

In [ ]:
weather_df

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017          31.0        9.0   Sunny
1/5/2017          -1.0        8.0    Snow
1/6/2017          30.0        7.0   Sunny
1/7/2017          32.0        NaN    Rain
1/8/2017           NaN        NaN   Sunny
1/9/2017           NaN        NaN     NaN
1/10/2017         34.0        8.0  Cloudy
1/11/2017         -4.0        NaN    Snow
1/12/2017         26.0       12.0   Sunny
1/13/2017         12.0       12.0   Rainy
1/11/2017         -1.0       12.0    Snow
1/14/2017         40.0        NaN   Sunny

In [ ]:
weather_df[weather_df['temperature'] > 30]

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017          31.0        9.0   Sunny
1/7/2017          32.0        NaN    Rain
1/10/2017         34.0        8.0  Cloudy
1/14/2017         40.0        NaN   Sunny

In [ ]:
weather_df[weather_df['event'] == "Rain"]

          temperature  windspeed event
day
1/1/2017         32.0        6.0  Rain
1/7/2017         32.0        NaN  Rain

In [ ]:
weather_df[weather_df['windspeed'] < 10]

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017          31.0        9.0   Sunny
1/5/2017          -1.0        8.0    Snow
1/6/2017          30.0        7.0   Sunny
1/10/2017         34.0        8.0  Cloudy

In [ ]:
car_details_df = pd.read_csv('./csv_data/car_details.csv')
car_details_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
maruti_800_ac_df = car_details_df[car_details_df['name'] == "Maruti 800 AC"]
maruti_800_ac_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
13,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
175,Maruti 800 AC,2007,95000,100000,Petrol,Individual,Manual,Second Owner
259,Maruti 800 AC,2002,65000,100000,Petrol,Individual,Manual,Second Owner
372,Maruti 800 AC,2000,60000,40000,Petrol,Individual,Manual,Third Owner

In [ ]:
maruti_800_ac_df['selling_price'].min()

40000

In [ ]:
maruti_800_ac_df['selling_price'].max()

225000

In [ ]:
maruti_800_ac_df['selling_price'].mean()

94347.82608695653

In [ ]:
car_details_df[car_details_df['name'] == "Maruti 800 AC"]['selling_price'].mean()

94347.82608695653

In [ ]:
car_details_df.loc[car_details_df['name'] == "Maruti 800 AC", "selling_price"].mean()

94347.82608695653

In [ ]:
car_details_df.loc[car_details_df['year'] == 2012, 'selling_price'].min()

35000

In [ ]:
car_details_df.loc[car_details_df['year'] == 2012, 'selling_price'].max()

2500000

In [ ]:
car_details_df.loc[car_details_df['year'] == 2012, 'selling_price'].mean()

371628.8530120482

In [ ]:
car_details_df.loc[car_details_df['selling_price'] > 100000, "name"].value_counts().head()

Maruti Swift Dzire VDI    69
Maruti Alto 800 LXI       55
Hyundai EON Era Plus      35
Maruti Swift VDI BSIV     29
Maruti Alto LXi           28
Name: name, dtype: int64

In [ ]:
car_details_df.loc[car_details_df['selling_price'] < 100000, "name"].value_counts().head()

Maruti 800 AC            15
Tata Indica GLS BS IV    14
Maruti Alto LXi          12
Maruti Wagon R LXI       12
Hyundai Santro GS        12
Name: name, dtype: int64

In [ ]:
car_details_df.loc[((car_details_df['selling_price'] < 80000) &
                   (car_details_df['owner'] == "Second Owner")),
                    "name"].value_counts().head()

Maruti Alto LXi          5
Tata Indica GLS BS IV    5
Maruti 800 AC            4
Maruti Wagon R LXI       4
Maruti Alto LXI          4
Name: name, dtype: int64

In [ ]:
car_details_df.loc[((car_details_df['name'] == "Maruti Swift Dzire VDI") |
                   (car_details_df['name'] == "Maruti Alto 800 LXI"))].shape

(128, 8)

In [ ]:
isinNamelist = ["Maruti Swift Dzire VDI", "Maruti Alto 800 LXI", "Maruti Alto LXi",
"Maruti Alto LX", "Hyundai EON Era Plus", "Maruti Swift VDI BSIV",
 "Maruti Wagon R VXI BS IV", "Maruti Swift VDI", "Hyundai EON Magna Plus",
 "Maruti Wagon R LXI Minor"]

In [ ]:
car_details_df['top10counts'] =0

In [ ]:
car_details_df.loc[car_details_df['name'].isin(isinNamelist),
               "top10counts"] = 1

In [ ]:
car_details_df['top10counts'].value_counts()

0    3962
1     378
Name: top10counts, dtype: int64

### Using Pandas Method To Create a Boolean Mask

<li>In the last couple lessons, we used Python boolean operators to create boolean masks to select subsets of data.</li>
    
<li>There are also a number of pandas methods that return boolean masks useful for exploring data.</li>

<li>Two examples are the Series.isnull() method and Series.notnull() method.</li>
<li>Series.isnull() method can be used to select either rows that contain null (or NaN) values for a certain column.</li>
<li>Similarly, Series.notnull() method is used to select rows that do not contain null values for a certain column.</li>

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data_nan.csv')
weather_df.head()

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0   Sunny
2  1/5/2017         -1.0        NaN    Snow
3  1/6/2017          NaN        7.0     NaN
4  1/7/2017         32.0        NaN    Rain

In [ ]:
weather_df[weather_df['temperature'].isnull()]

        day  temperature  windspeed   event
1  1/4/2017          NaN        9.0   Sunny
3  1/6/2017          NaN        7.0     NaN
5  1/8/2017          NaN        NaN   Sunny
6  1/9/2017          NaN        NaN     NaN

In [ ]:
weather_df[weather_df['temperature'].notnull()]

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0   Rain
2    1/5/2017         -1.0        NaN    Snow
4    1/7/2017         32.0        NaN    Rain
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0        NaN    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0        NaN   Sunny

In [ ]:
weather_df[(weather_df['temperature'].notnull()) &
(weather_df['windspeed'].notnull()) &
(weather_df['event'].notnull())]

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0   Rain
7   1/10/2017         34.0        8.0  Cloudy
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow

#### Question 1

<li>Read 'Fortune_1000.csv' file using pandas read_csv() method and store it in a variable named f1000.</li>
<li>Select the rank, revenues, and rank_change columns in f1000. Then, use the df.head() method to select first five rows.</li>
<li>Select just the fifth row of the f1000 dataframe. Assign the result to fifth_row using iloc.</li>
<li>Select the value in first row of the company column. Assign the result to company_value.</li>
<li>Select the last three rows of the f1000 dataframe. Assign the result to last_three_rows.</li>
<li>Select the first to seventh rows and the first five columns of the f1000 dataframe.</li>

In [ ]:
import pandas as pd
f1000 = pd.read_csv('./csv_data/Fortune_1000.csv', na_values = " ")
f1000.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468

In [ ]:
f1000.columns

Index(['company', 'rank', 'rank_change', 'revenue', 'profit',
       'num. of employees', 'sector', 'city', 'state', 'newcomer',
       'ceo_founder', 'ceo_woman', 'profitable', 'prev_rank', 'CEO', 'Website',
       'Ticker', 'Market Cap'],
      dtype='object')

In [ ]:
f1000.shape

(1000, 18)

In [ ]:
f1000_selection = f1000[['rank', 'rank_change', 'revenue']]
print(f1000_selection.shape)
f1000_selection.head()

(1000, 3)

   rank  rank_change   revenue
0     1          0.0  572754.0
1     2          0.0  469822.0
2     3          0.0  365817.0
3     4          0.0  292111.0
4     5          0.0  287597.0

In [ ]:
fifth_row = f1000.iloc[4,:]
print(fifth_row)

company                     UnitedHealth Group
rank                                         5
rank_change                                0.0
revenue                               287597.0
profit                                 17285.0
num. of employees                     350000.0
sector                             Health Care
city                                Minnetonka
state                                       MN
newcomer                                    no
ceo_founder                                 no
ceo_woman                                   no
profitable                                 yes
prev_rank                                  5.0
CEO                            Andrew P. Witty
Website              www.unitedhealthgroup.com
Ticker                                     UNH
Market Cap                              500468
Name: 4, dtype: object

In [ ]:
company_value = f1000.loc[0, 'company']
print(company_value)

Walmart

In [ ]:
last_three_rows = f1000[-3:]
last_three_rows.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
997,Cowen,998,0.0,2112.8,295.6,1534.0,Financials,New York,NY,no,no,no,yes,NaN,Jeffrey Solomon,https://www.cowen.com,COWN,1078
998,Ashland,999,0.0,2111.0,220.0,4100.0,Chemicals,Wilmington,DE,no,no,no,yes,NaN,Guillermo Novo,https://www.ashland.com,ASH,5601.9
999,DocuSign,1000,0.0,2107.2,-70.0,7461.0,Technology,San Francisco,CA,no,no,no,no,NaN,Allan C. Thygesen,https://www.docusign.com,DOCU,21302.8

In [ ]:
first_to_seven_rows = f1000.iloc[:7, :5]
first_to_seven_rows.head()

              company  rank  rank_change   revenue   profit
0             Walmart     1          0.0  572754.0  13673.0
1              Amazon     2          0.0  469822.0  33364.0
2               Apple     3          0.0  365817.0  94680.0
3          CVS Health     4          0.0  292111.0   7910.0
4  UnitedHealth Group     5          0.0  287597.0  17285.0

#### Question 2
<li>Use the Series.isnull() method to select all rows from f1000 that have a null value for the prev_rank column.</li>
<li>Select only the company, rank, and previous_rank columns where previous_rank column is null.</li>
<li>Use the Series.notnull() method to select all rows from f1000 that have a non-null value for the previous_rank column.</li></b>
<li>From the previously_ranked dataframe, subtract the rank column from the previous_rank column.</li>
<li>Assign the values in the rank_change to a new column in the f1000 dataframe, "rank_change".</li>

In [ ]:
null_prev_rank = f1000[f1000['prev_rank'].isnull()]
null_prev_rank.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
170,Cleveland-Cliffs,171,0.0,20444.0,2988.0,26000.0,Materials,Cleveland,OH,yes,no,no,yes,NaN,C. Lourenco Goncalves,https://www.clevelandcliffs.com,CLF,16891.2
194,Moderna,195,0.0,18471.0,12202.0,2700.0,Health Care,Cambridge,MA,yes,no,no,yes,NaN,Stephane Bancel,https://www.modernatx.com,MRNA,69424.3
308,Devon Energy,309,0.0,12206.0,2813.0,1600.0,Energy,Oklahoma City,OK,yes,no,no,yes,NaN,Richard E. Muncrief,https://www.devonenergy.com,DVN,39274.1
321,International Flavors & Fragrances,322,0.0,11656.0,270.0,24000.0,Chemicals,New York,NY,yes,no,no,yes,NaN,Franklin K. Clyburn Jr.,https://www.iff.com,IFF,33455.6
334,Caesars Entertainment,335,0.0,11110.0,-1019.0,49000.0,"Hotels, Restaurants & Leisure",Reno,NV,yes,no,no,no,NaN,Thomas R. Reeg,https://www.caesars.com,CZR,16564.6

In [ ]:
null_previous_rank = f1000.loc[f1000['prev_rank'].isnull(),['company', 'rank', 'prev_rank']]
null_previous_rank.head()

                                company  rank  prev_rank
170                    Cleveland-Cliffs   171        NaN
194                             Moderna   195        NaN
308                        Devon Energy   309        NaN
321  International Flavors & Fragrances   322        NaN
334               Caesars Entertainment   335        NaN

In [ ]:
not_null_prev_rank = f1000[f1000['prev_rank'].notnull()]
not_null_prev_rank.shape

(469, 18)

In [ ]:
f1000['rank_change'] = f1000['prev_rank'] - f1000['rank']

In [ ]:
f1000.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468

In [ ]:
# df.info()

#### Question 3
<li>Select all companies with revenues over 100 thousands and negative profits from the f1000 dataframe.</li>

##### Instructions

<li>Create a boolean array that selects the companies with revenues greater than 100 thousands.</li>
<li>Create a boolean array that selects the companies with profits less than 0.</li>

In [ ]:
f1000[(f1000['revenue'] > 100000) &
     (f1000['profit'] < 0)]

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
8,McKesson,9,-2.0,238228.0,-4539.0,67500.0,Health Care,Irving,TX,no,no,no,no,7.0,Brian S. Tyler,www.mckesson.com,MCK,47377

#### Question 4
<li>Select all rows for companies whose city value is either Brazil or Venezuela.</li>
<li>Select the first five companies in the Technology sector for which the city is not the "Boston" from the f1000 dataframe.</li>

In [ ]:
f1000.loc[(f1000['city'] == "New York") |
         (f1000['city']=="San Fransciso")]

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
22,Verizon Communications,23,-3.0,133613.0,22065.0,118400.0,Telecommunications,New York,NY,no,no,no,yes,20.0,Hans E. Vestberg,www.verizon.com,VZ,211872
23,JPMorgan Chase,24,-5.0,127202.0,48334.0,271025.0,Financials,New York,NY,no,no,no,yes,19.0,James Dimon,www.jpmorganchase.com,JPM,336469
42,Pfizer,43,34.0,81288.0,21979.0,79000.0,Health Care,New York,NY,no,no,no,yes,77.0,Albert Bourla,www.pfizer.com,PFE,288232
43,Citigroup,44,-11.0,79865.0,21952.0,221768.0,Financials,New York,NY,no,no,yes,yes,33.0,Jane Fraser,www.citigroup.com,C,100976
49,MetLife,50,-4.0,71080.0,6554.0,43000.0,Financials,New York,NY,no,no,no,yes,46.0,Michel A. Khalaf,www.metlife.com,MET,49443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,G-III Apparel Group,885,NaN,2766.5,200.6,3250.0,Apparel,New York,NY,no,no,no,yes,NaN,Morris Goldfarb,https://www.giii.com,GIII,1296.1
913,WeWork,914,NaN,2570.1,-4439.0,4400.0,Financials,New York,NY,no,no,no,no,NaN,Sandeep Mathrani,https://www.wework.com,WE,4937.4
918,Griffon,919,NaN,2541.7,79.2,6700.0,Materials,New York,NY,no,no,no,yes,NaN,Ronald J. Kramer,https://www.griffon.com,GFF,1127.8
955,Signature Bank,956,NaN,2311.3,918.4,1854.0,Financials,New York,NY,no,yes,no,yes,NaN,Joseph J. DePaolo,https://www.signatureny.com,SBNY,18416.9
997,Cowen,998,NaN,2112.8,295.6,1534.0,Financials,New York,NY,no,no,no,yes,NaN,Jeffrey Solomon,https://www.cowen.com,COWN,1078

In [ ]:
f1000.loc[(f1000['city'] != "Boston")].head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468

#### Sorting Values
<li>We can use the DataFrame.sort_values() method to sort the rows on a particular column.</li>
<li>To do so, we pass the column name to the method:</li>
<code>
sorted_rows = df.sort_values("column_name")
</code>
<li>By default, the sort_values() method will sort the rows in ascending order — from smallest to largest.</li>
<li>To sort the rows in descending order instead, we can set the ascending parameter to False:</li>
<code>
    sorted_rows = df.sort_values("column_name", ascending=False)
</code>

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data_nan.csv')
weather_df.head()

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0   Sunny
2  1/5/2017         -1.0        NaN    Snow
3  1/6/2017          NaN        7.0     NaN
4  1/7/2017         32.0        NaN    Rain

In [ ]:
weather_df.sort_values('temperature', ascending = True, inplace = True)
weather_df.head()

          day  temperature  windspeed  event
8   1/11/2017         -4.0        NaN   Snow
2    1/5/2017         -1.0        NaN   Snow
11  1/11/2017         -1.0       12.0   Snow
10  1/13/2017         12.0       12.0  Rainy
9   1/12/2017         26.0       12.0  Sunny

In [ ]:
weather_df.sort_values('windspeed', ascending = False, inplace = True)
weather_df.head()

          day  temperature  windspeed   event
11  1/11/2017         -1.0       12.0    Snow
10  1/13/2017         12.0       12.0   Rainy
9   1/12/2017         26.0       12.0   Sunny
1    1/4/2017          NaN        9.0   Sunny
7   1/10/2017         34.0        8.0  Cloudy

In [ ]:
weather_df.sort_values('event', ascending = True, inplace = True)
weather_df.head()

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0   Rain
2    1/5/2017         -1.0        NaN    Snow
1    1/4/2017          NaN        9.0   Sunny
12  1/14/2017         40.0        NaN   Sunny
7   1/10/2017         34.0        8.0  Cloudy

In [ ]:
f1000.sort_values(['rank_change', 'revenue', 'profit'],
                 ascending = [True, False, False], inplace = True)
f1000.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
434,Bath & Body Works,435,-178.0,7881.5,1333.5,32850.0,Retailing,Columbus,OH,no,no,yes,yes,257.0,Sarah E. Nash,https://www.bbwinc.com,BBWI,11419.9
379,VF Corp.,380,-117.0,9238.8,407.9,33600.0,Apparel,Denver,CO,no,no,no,yes,263.0,Steven Rendle,https://www.vfc.com,VFC,11620
467,Brighthouse Financial,468,-115.0,7142.0,-108.0,1500.0,Financials,Charlotte,NC,no,no,no,no,353.0,Eric T. Steigerwalt,https://www.brighthousefinancial.com,BHF,3958.7
337,Biogen,338,-110.0,10981.7,1556.1,9610.0,Health Care,Cambridge,MA,no,no,no,yes,228.0,Michel Vounatsos,https://www.biogen.com,BIIB,30950.4
290,XPO Logistics,291,-101.0,12806.0,336.0,44700.0,Transportation,Greenwich,CT,no,no,no,yes,190.0,Brad Jacobs,https://www.xpo.com,XPO,8356.9

In [ ]:
f1000.describe()

,rank,rank_change,revenue,profit,num. of employees,prev_rank
count,1000.000000,469.000000,1000.000000,997.000000,9.990000e+02,469.000000
mean,500.497000,-1.428571,17986.801400,2026.476329,3.578867e+04,237.763326
std,288.818067,46.455310,40813.281554,6421.578081,1.046546e+05,138.735766
min,1.000000,-178.000000,2107.200000,-6520.000000,1.600000e+02,1.000000
25%,250.750000,-23.000000,3500.750000,195.400000,6.500000e+03,118.000000
50%,500.500000,-5.000000,6375.500000,572.000000,1.353000e+04,237.000000
75%,750.250000,10.000000,14615.475000,1498.300000,2.890000e+04,355.000000
max,1000.000000,295.000000,572754.000000,94680.000000,2.300000e+06,498.000000

#### Question
<li>Read 'Fortune_1000.csv' using pandas read_csv() method.</li>
<li>Find the company headquartered in Los Angeles with the largest number of employees.</li>
<li>Select only the rows that have a city name equal to Los Angeles.</li>
<li>Use DataFrame.sort_values() to sort those rows by the employees column in descending order.</li>
<li>Use DataFrame.iloc[] to select the first row from the sorted dataframe.</li>

In [ ]:
f1000 = pd.read_csv('./csv_data/Fortune_1000.csv', na_values = " ")
f1000.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468

In [ ]:
los_angeles_df = f1000[f1000['city'] == "Los Angeles"].sort_values('num. of employees',
                                                 ascending = False)
los_angeles_df.iloc[:1]

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
260,Reliance Steel & Aluminum,261,82.0,14093.3,1413.0,13950.0,Materials,Los Angeles,CA,no,no,no,yes,343.0,James D. Hoffman,https://www.rsac.com,RS,11313.5

### String Manipulation In Pandas DataFrame

<li>String manipulation is the process of changing, parsing, splitting, 'cleaning' or analyzing strings.</li>
<li>As we know that sometimes, data in the string is not suitable for manipulating the analysis or get a description of the data.</li>
<li>But Python is known for its ability to manipulate strings.</li>
<li>Pandas provides us the ways to manipulate to modify and process string data-frame using some builtin functions.</li>
<li>Some of the most useful pandas string processing functions are as follows:</li>
<ol>
    <li><b>lower()</b></li>
    <li><b>upper()</b></li>
    <li><b>islower()</b></li>
    <li><b>isupper()</b></li>
    <li><b>isnumeric()</b></li>
    <li><b>strip()</b></li>
    <li><b>split()</b></li>
    <li><b>len()</b></li>
    <li><b>get_dummies()</b></li>
    <li><b>startswith()</b></li>
    <li><b>endswith()</b></li>
    <li><b>replace()</b></li>
    <li><b>contains()</b></li>
</ol>

#### 1. lower():
<li>It converts all uppercase characters in strings in the dataframe to lower case and returns the lowercase strings in the result.</li>

In [ ]:
weather_df.head()

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0   Rain
2    1/5/2017         -1.0        NaN    Snow
1    1/4/2017          NaN        9.0   Sunny
12  1/14/2017         40.0        NaN   Sunny
7   1/10/2017         34.0        8.0  Cloudy

In [ ]:
weather_df['event'] = weather_df['event'].str.lower()

In [ ]:
weather_df.head()

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0   rain
2    1/5/2017         -1.0        NaN    snow
1    1/4/2017          NaN        9.0   sunny
12  1/14/2017         40.0        NaN   sunny
7   1/10/2017         34.0        8.0  cloudy

#### 2. upper():
<li>It converts all lowercase characters in strings in the dataframe to upper case and returns the uppercase strings in result.</li>

In [ ]:
weather_df['event'] = weather_df['event'].str.upper()
weather_df.head()

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0   RAIN
2    1/5/2017         -1.0        NaN    SNOW
1    1/4/2017          NaN        9.0   SUNNY
12  1/14/2017         40.0        NaN   SUNNY
7   1/10/2017         34.0        8.0  CLOUDY

#### 3. islower():
<li>It checks whether all characters in each string in the Data-Frame is in lower case or not, and returns a Boolean value.</li>

In [ ]:
weather_df['event'].str.islower()

0     False
2     False
1     False
12    False
7     False
4     False
10    False
11    False
8     False
9     False
5     False
3       NaN
6       NaN
Name: event, dtype: object

In [ ]:
weather_df['event'] = weather_df['event'].str.lower()

In [ ]:
weather_df['event'].str.islower()

0     True
2     True
1     True
12    True
7     True
4     True
10    True
11    True
8     True
9     True
5     True
3      NaN
6      NaN
Name: event, dtype: object

#### 4. isupper():
<li>It checks whether all characters in each string in the Data-Frame is in upper case or not, and returns a Boolean value.</li>

In [ ]:
weather_df['event'].str.isupper()

0     False
2     False
1     False
12    False
7     False
4     False
10    False
11    False
8     False
9     False
5     False
3       NaN
6       NaN
Name: event, dtype: object

In [ ]:
import warnings
warnings.filterwarnings('ignore')
weather_df['event'][:5] = weather_df['event'][:5].str.upper()

In [ ]:
weather_df['event'].str.isupper()

0      True
2      True
1      True
12     True
7      True
4     False
10    False
11    False
8     False
9     False
5     False
3       NaN
6       NaN
Name: event, dtype: object

#### 5. isnumeric():
<li>It checks whether all characters in each string in the Data-Frame are numeric or not, and returns a Boolean value.</li>

In [ ]:
import pandas as pd

series = pd.Series(['one', '1', 'two', '2'])
series

0    one
1      1
2    two
3      2
dtype: object

In [ ]:
series.str.isnumeric()

0    False
1     True
2    False
3     True
dtype: bool

#### 6. strip():
<li>If there are spaces at the beginning or end of a string, we should trim the strings to eliminate spaces using strip() method.</li>
<li>It remove the extra spaces contained by a string in a DataFrame.</li>

In [ ]:
example_string = " Butwal "
print(example_string)
print(len(example_string))

 Butwal
8

In [ ]:
strip_example_string = example_string.strip()
print(strip_example_string)
print(len(strip_example_string))

Butwal
6

In [ ]:
weather_df = pd.read_csv('weather_data_nan.csv')
weather_df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         -1.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

In [ ]:
weather_df['strip_event'] = weather_df['event'].str.strip()

In [ ]:
weather_df['event_lenght'] = weather_df['event'].str.len()
weather_df['strip_event_length'] = weather_df['strip_event'].str.len()

In [ ]:
weather_df[['event', 'strip_event', 'event_lenght', 'strip_event_length']]

     event strip_event  event_lenght  strip_event_length
0     Rain        Rain           4.0                 4.0
1    Sunny       Sunny           5.0                 5.0
2     Snow        Snow           4.0                 4.0
3      NaN         NaN           NaN                 NaN
4     Rain        Rain           4.0                 4.0
5    Sunny       Sunny           5.0                 5.0
6      NaN         NaN           NaN                 NaN
7   Cloudy      Cloudy           6.0                 6.0
8     Snow        Snow           4.0                 4.0
9    Sunny       Sunny           5.0                 5.0
10   Rainy       Rainy           5.0                 5.0
11    Snow        Snow           4.0                 4.0
12   Sunny       Sunny           5.0                 5.0

#### 7. split(‘ ‘):
<li>It splits each string with the given pattern.</li>
<li>Strings are split and the new elements after the performed split operation, are stored in a list.</li>

In [ ]:
df = pd.read_csv('./csv_data/Fortune_1000.csv', na_values = " ")
df.head()

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468

In [ ]:
df['top_level_domain'] = df['Website'].str.split('.').str[-1]

In [ ]:
df[['Website', 'top_level_domain']]

                           Website top_level_domain
0    https://www.stock.walmart.com              com
1                   www.amazon.com              com
2                    www.apple.com              com
3        https://www.cvshealth.com              com
4        www.unitedhealthgroup.com              com
..                             ...              ...
995          https://www.vizio.com              com
996    https://www.1800flowers.com              com
997          https://www.cowen.com              com
998        https://www.ashland.com              com
999       https://www.docusign.com              com

[1000 rows x 2 columns]

In [ ]:
df['top_level_domain'].value_counts()

com           984
net             6
xyz             2
org             2
tv              2
technology      1
com/corp        1
com/            1
us              1
Name: top_level_domain, dtype: int64

#### 8. len():
<li>With the help of len() we can compute the length of each string in DataFrame.</li>
<li>If there is empty data in a DataFrame, it returns NaN.</li>

In [ ]:
df['companyname_length'] = df['company'].str.len()

In [ ]:
df[['company', 'companyname_length']]

                company  companyname_length
0               Walmart                   7
1                Amazon                   6
2                 Apple                   5
3            CVS Health                  10
4    UnitedHealth Group                  18
..                  ...                 ...
995       Vizio Holding                  13
996   1-800-Flowers.com                  17
997               Cowen                   5
998             Ashland                   7
999            DocuSign                   8

[1000 rows x 2 columns]

#### 9. get_dummies():
<li>It returns the DataFrame with One-Hot Encoded values like we can see that it returns boolean value 1 if it exists in relative index or 0 if not exists.</li>

In [ ]:
weather_df['strip_event'].str.get_dummies()

    Cloudy  Rain  Rainy  Snow  Sunny
0        0     1      0     0      0
1        0     0      0     0      1
2        0     0      0     1      0
3        0     0      0     0      0
4        0     1      0     0      0
5        0     0      0     0      1
6        0     0      0     0      0
7        1     0      0     0      0
8        0     0      0     1      0
9        0     0      0     0      1
10       0     0      1     0      0
11       0     0      0     1      0
12       0     0      0     0      1

In [ ]:
car_details_df['fuel'].str.get_dummies()

      CNG  Diesel  Electric  LPG  Petrol
0       0       0         0    0       1
1       0       0         0    0       1
2       0       1         0    0       0
3       0       0         0    0       1
4       0       1         0    0       0
...   ...     ...       ...  ...     ...
4335    0       1         0    0       0
4336    0       1         0    0       0
4337    0       0         0    0       1
4338    0       1         0    0       0
4339    0       0         0    0       1

[4340 rows x 5 columns]

#### 10. startswith(pattern):
<li>It returns true if the element or string in the DataFrame Index starts with the pattern.</li>
<li>If you wanted to filter out rows that startswith 'ind' then you can specify df[df[col].str.startswith('ind')</li>

In [ ]:
car_details_df[car_details_df['name'].str.startswith('Maruti')]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,top10counts
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,0
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,1
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner,0
9,Maruti Celerio Green VXI,2017,365000,78000,CNG,Individual,Manual,First Owner,0
13,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,0
...,...,...,...,...,...,...,...,...,...
4323,Maruti 800 AC,2014,195000,75000,Petrol,Individual,Manual,Second Owner,0
4324,Maruti Alto 800 Base,2015,155000,40000,Petrol,Individual,Manual,First Owner,0
4325,Maruti Alto LXi,2000,65000,90000,Petrol,Individual,Manual,Second Owner,1
4333,Maruti Ritz VDi,2012,225000,90000,Diesel,Individual,Manual,Second Owner,0
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,0

In [ ]:
df[df['Website'].str.startswith('https')]

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap,top_level_domain,companyname_length
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037,com,7
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204,com,10
7,Alphabet,8,1.0,257637.0,76033.0,156500.0,Technology,Mountain View,CA,no,no,no,yes,9.0,Sundar Pichai,https://www.abc.xyz,GOOGL,1309359,xyz,8
11,Cigna,12,1.0,174078.0,5365.0,72963.0,Health Care,Bloomfield,CT,no,no,no,yes,13.0,David Cordani,https://www.cigna.com,CI,88459,com,5
26,Meta Platforms,27,7.0,117929.0,39370.0,71970.0,Technology,Menlo Park,CA,no,yes,no,yes,34.0,Mark Zuckerberg,https://investor.fb.com,META,475718,com,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Vizio Holding,996,0.0,2124.0,-39.4,800.0,Industrials,Irvine,CA,no,yes,no,no,NaN,William W. Wang,https://www.vizio.com,VZIO,1705.1,com,13
996,1-800-Flowers.com,997,0.0,2122.2,118.7,4800.0,Retailing,Jericho,NY,no,no,no,yes,NaN,Christopher G. McCann,https://www.1800flowers.com,FLWS,830,com,17
997,Cowen,998,0.0,2112.8,295.6,1534.0,Financials,New York,NY,no,no,no,yes,NaN,Jeffrey Solomon,https://www.cowen.com,COWN,1078,com,5
998,Ashland,999,0.0,2111.0,220.0,4100.0,Chemicals,Wilmington,DE,no,no,no,yes,NaN,Guillermo Novo,https://www.ashland.com,ASH,5601.9,com,7
999,DocuSign,1000,0.0,2107.2,-70.0,7461.0,Technology,San Francisco,CA,no,no,no,no,NaN,Allan C. Thygesen,https://www.docusign.com,DOCU,21302.8,com,8

#### 11. endswith(pattern):
<li>It returns true if the element or string in the DataFrame Index ends with the pattern.</li>
<li>If you wanted to filter out rows that ends with 'es' then you can specify df[df[col].str.endswith('es')</li>

In [ ]:
print(car_details_df[car_details_df['name'].str.endswith('AC')].shape)
car_details_df[car_details_df['name'].str.endswith('AC')]

(29, 9)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,top10counts
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,0
13,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,0
175,Maruti 800 AC,2007,95000,100000,Petrol,Individual,Manual,Second Owner,0
259,Maruti 800 AC,2002,65000,100000,Petrol,Individual,Manual,Second Owner,0
372,Maruti 800 AC,2000,60000,40000,Petrol,Individual,Manual,Third Owner,0
402,Maruti 800 AC,2007,105000,60000,Petrol,Individual,Manual,Second Owner,0
669,Maruti 800 AC,2012,180000,120000,Petrol,Individual,Manual,First Owner,0
1284,Maruti 800 AC,2002,65000,100000,Petrol,Individual,Manual,Second Owner,0
1446,Maruti 800 AC,2002,80000,70000,Petrol,Individual,Manual,Second Owner,0
1726,Maruti 800 AC,2009,125000,50000,Petrol,Individual,Manual,Fourth & Above Owner,0
2386,Maruti Eeco Smiles 5 Seater AC,2014,325000,30000,Petrol,Dealer,Manual,First Owner,0
3181,Maruti 800 AC,2013,100000,80000,Petrol,Individual,Manual,First Owner,0
3215,Maruti 800 AC,2004,40000,69111,Petrol,Individual,Manual,Third Owner,0
3217,Maruti 800 AC,2007,80000,120000,Petrol,Individual,Manual,First Owner,0
3259,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,0
3285,Maruti 800 AC,2014,225000,35000,Petrol,Individual,Manual,First Owner,0
3314,Maruti 800 AC,2008,90000,70000,Petrol,Individual,Manual,Third Owner,0
3377,Maruti Eeco Smiles 5 Seater AC,2016,330000,72500,Petrol,Dealer,Manual,First Owner,0
3378,Maruti Eeco Smiles 5 Seater AC,2013,280000,76600,Petrol,Dealer,Manual,First Owner,0
3503,Maruti 800 AC,2002,80000,40000,Petrol,Individual,Manual,Fourth & Above Owner,0
3630,Maruti 800 AC,2006,100000,54000,Petrol,Individual,Manual,First Owner,0
3652,Maruti 800 AC,2008,80000,50000,Petrol,Individual,Manual,Second Owner,0
3740,Maruti 800 AC,2006,55000,70000,Petrol,Individual,Manual,Second Owner,0
3856,Maruti 800 AC,1999,50000,100000,Petrol,Individual,Manual,Second Owner,0
3912,Ambassador CLASSIC 1500 DSL AC,2005,120000,50000,Diesel,Individual,Manual,Second Owner,0
4016,Ambassador CLASSIC 1500 DSL AC,2005,120000,50000,Diesel,Individual,Manual,Second Owner,0
4060,Mahindra Thar CRDe AC,2014,600000,100000,Diesel,Individual,Manual,Second Owner,0
4088,Maruti 800 AC,2009,120000,250000,Petrol,Individual,Manual,Second Owner,0
4323,Maruti 800 AC,2014,195000,75000,Petrol,Individual,Manual,Second Owner,0

#### 12. replace(a,b):
<li>It replaces the value a with the value b.</li>
<li>If you wanted to remove white space characters then you can use replace() method as:</li>
<code>
df[col_name].str.replace(" ", "")
</code>

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data_nan.csv')
weather_df.head()

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0   Sunny
2  1/5/2017         -1.0        NaN    Snow
3  1/6/2017          NaN        7.0     NaN
4  1/7/2017         32.0        NaN    Rain

In [ ]:
weather_df['event'] = weather_df['event'].str.replace(' ', '')

In [ ]:
weather_df.head(20)

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0        NaN    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0   Rainy
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0        NaN   Sunny

In [ ]:
weather_df['event'] = weather_df['event'].str.replace('Rainy', 'Rain')

In [ ]:
weather_df.tail()

          day  temperature  windspeed  event
8   1/11/2017         -4.0        NaN   Snow
9   1/12/2017         26.0       12.0  Sunny
10  1/13/2017         12.0       12.0   Rain
11  1/11/2017         -1.0       12.0   Snow
12  1/14/2017         40.0        NaN  Sunny

In [ ]:
appointment_df['app_start_date'] = appointment_df['app_start_date'].str.replace('/', '-')
appointment_df['app_end_date'] = appointment_df['app_end_date'].str.replace('/', '-')

In [ ]:
appointment_df.head()

,name,appointment_made_date,app_start_date,app_end_date,visitee_namelast,visitee_namefirst,meeting_room,description
0,Joshua T. Blanton,2014-12-18T00:00:00,1-6-15 9:30,1-6-15 23:59,NaN,potus,west wing,JointService Military Honor Guard
1,Jack T. Gutting,2014-12-18T00:00:00,1-6-15 9:30,1-6-15 23:59,NaN,potus,west wing,JointService Military Honor Guard
2,Bradley T. Guiles,2014-12-18T00:00:00,1-6-15 9:30,1-6-15 23:59,NaN,potus,west wing,JointService Military Honor Guard
3,Loryn F. Grieb,2014-12-18T00:00:00,1-6-15 9:30,1-6-15 23:59,NaN,potus,west wing,JointService Military Honor Guard
4,Travis D. Gordon,2014-12-18T00:00:00,1-6-15 9:30,1-6-15 23:59,NaN,potus,west wing,JointService Military Honor Guard

#### 13. contains():
<li>contains() method checks whether the string contains a particular substring or not.</li>
<li>The function is quite similar to replace() but instead of replacing the string itself it just returns the boolean value True or False.</li>
<li>If a substring is present in a string, then it returns boolean value True else False.</li>

In [ ]:
appointment_df = pd.read_csv('./csv_data/appointment_schedule.csv')
appointment_df.head()

,name,appointment_made_date,app_start_date,app_end_date,visitee_namelast,visitee_namefirst,meeting_room,description
0,Joshua T. Blanton,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
1,Jack T. Gutting,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
2,Bradley T. Guiles,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
3,Loryn F. Grieb,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
4,Travis D. Gordon,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard

In [ ]:
appointment_df['description'].isnull().sum()

372

In [ ]:
appointment_df[appointment_df['description'].str.contains('Military',
                                                         na = False)]

,name,appointment_made_date,app_start_date,app_end_date,visitee_namelast,visitee_namefirst,meeting_room,description
0,Joshua T. Blanton,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
1,Jack T. Gutting,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
2,Bradley T. Guiles,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
3,Loryn F. Grieb,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
4,Travis D. Gordon,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
...,...,...,...,...,...,...,...,...
90,Jacob P. Loos,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
91,Brian T. McCrum,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
92,Mack D. Mccartney,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
93,Isaac E. Porter,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard
94,Garret B. Shultz,2014-12-18T00:00:00,1/6/15 9:30,1/6/15 23:59,NaN,potus,west wing,JointService Military Honor Guard

#### Handling Missing Values
<li>We can use fillna() method in pandas to fill missing values using different ways.</li>
<li>We can use interpolation method to make a guess on missing values.</li>
<li>We can use dropna() method to drop rows with missing values.</li>
<li>We can also fill missing values with the mean value, median value or the mode value depending on the values of columns.</li>
<li>Filling missing values with mean and median is appropriate when the column has continuous values.</li>
<li>If the data is categorical then filling missing values with mode is a good idea.</li>

In [ ]:
weather_df

          day  temperature  windspeed   event
0    1/1/2017         32.0        6.0    Rain
1    1/4/2017          NaN        9.0   Sunny
2    1/5/2017         -1.0        NaN    Snow
3    1/6/2017          NaN        7.0     NaN
4    1/7/2017         32.0        NaN    Rain
5    1/8/2017          NaN        NaN   Sunny
6    1/9/2017          NaN        NaN     NaN
7   1/10/2017         34.0        8.0  Cloudy
8   1/11/2017         -4.0        NaN    Snow
9   1/12/2017         26.0       12.0   Sunny
10  1/13/2017         12.0       12.0    Rain
11  1/11/2017         -1.0       12.0    Snow
12  1/14/2017         40.0        NaN   Sunny

In [ ]:
weather_df['temperature_fillna_0'] = weather_df['temperature'].fillna(0)
weather_df

          day  temperature  windspeed   event  temperature_fillna_0
0    1/1/2017         32.0        6.0    Rain                  32.0
1    1/4/2017          NaN        9.0   Sunny                   0.0
2    1/5/2017         -1.0        NaN    Snow                  -1.0
3    1/6/2017          NaN        7.0     NaN                   0.0
4    1/7/2017         32.0        NaN    Rain                  32.0
5    1/8/2017          NaN        NaN   Sunny                   0.0
6    1/9/2017          NaN        NaN     NaN                   0.0
7   1/10/2017         34.0        8.0  Cloudy                  34.0
8   1/11/2017         -4.0        NaN    Snow                  -4.0
9   1/12/2017         26.0       12.0   Sunny                  26.0
10  1/13/2017         12.0       12.0    Rain                  12.0
11  1/11/2017         -1.0       12.0    Snow                  -1.0
12  1/14/2017         40.0        NaN   Sunny                  40.0

In [ ]:
weather_df['temperature_fillna_mean'] = weather_df['temperature'].fillna(weather_df['temperature'].mean())
weather_df['temperature_fillna_mean'] = weather_df['temperature_fillna_mean'].round(2)

In [ ]:
weather_df

,day,temperature,windspeed,event,temperature_fillna_0,temperature_fillna_mean
0,1/1/2017,32.0,6.0,Rain,32.0,32.00
1,1/4/2017,NaN,9.0,Sunny,0.0,18.89
2,1/5/2017,-1.0,NaN,Snow,-1.0,-1.00
3,1/6/2017,NaN,7.0,NaN,0.0,18.89
4,1/7/2017,32.0,NaN,Rain,32.0,32.00
5,1/8/2017,NaN,NaN,Sunny,0.0,18.89
6,1/9/2017,NaN,NaN,NaN,0.0,18.89
7,1/10/2017,34.0,8.0,Cloudy,34.0,34.00
8,1/11/2017,-4.0,NaN,Snow,-4.0,-4.00
9,1/12/2017,26.0,12.0,Sunny,26.0,26.00
10,1/13/2017,12.0,12.0,Rain,12.0,12.00
11,1/11/2017,-1.0,12.0,Snow,-1.0,-1.00
12,1/14/2017,40.0,NaN,Sunny,40.0,40.00

In [ ]:
median = weather_df['windspeed'].median()
weather_df['windspeed_fillna_median'] = weather_df['windspeed'].fillna(median)

In [ ]:
weather_df[['day', 'windspeed', 'windspeed_fillna_median']]

          day  windspeed  windspeed_fillna_median
0    1/1/2017        6.0                      6.0
1    1/4/2017        9.0                      9.0
2    1/5/2017        NaN                      9.0
3    1/6/2017        7.0                      7.0
4    1/7/2017        NaN                      9.0
5    1/8/2017        NaN                      9.0
6    1/9/2017        NaN                      9.0
7   1/10/2017        8.0                      8.0
8   1/11/2017        NaN                      9.0
9   1/12/2017       12.0                     12.0
10  1/13/2017       12.0                     12.0
11  1/11/2017       12.0                     12.0
12  1/14/2017        NaN                      9.0

In [ ]:
mode = weather_df['event'].mode()[0]
weather_df['event_fillna_mode'] =  weather_df['event'].fillna(mode)

In [ ]:
weather_df[['day', 'event', 'event_fillna_mode']]

          day   event event_fillna_mode
0    1/1/2017    Rain              Rain
1    1/4/2017   Sunny             Sunny
2    1/5/2017    Snow              Snow
3    1/6/2017     NaN             Sunny
4    1/7/2017    Rain              Rain
5    1/8/2017   Sunny             Sunny
6    1/9/2017     NaN             Sunny
7   1/10/2017  Cloudy            Cloudy
8   1/11/2017    Snow              Snow
9   1/12/2017   Sunny             Sunny
10  1/13/2017    Rain              Rain
11  1/11/2017    Snow              Snow
12  1/14/2017   Sunny             Sunny

#### fillna(method = 'ffill')

In [ ]:
weather_df['ffill_temperature'] = weather_df['temperature'].fillna(method = 'ffill')

In [ ]:
weather_df[['day', 'temperature', 'ffill_temperature']]

          day  temperature  ffill_temperature
0    1/1/2017         32.0               32.0
1    1/4/2017          NaN               32.0
2    1/5/2017         -1.0               -1.0
3    1/6/2017          NaN               -1.0
4    1/7/2017         32.0               32.0
5    1/8/2017          NaN               32.0
6    1/9/2017          NaN               32.0
7   1/10/2017         34.0               34.0
8   1/11/2017         -4.0               -4.0
9   1/12/2017         26.0               26.0
10  1/13/2017         12.0               12.0
11  1/11/2017         -1.0               -1.0
12  1/14/2017         40.0               40.0

#### fillna(method = 'bfill')

In [ ]:
import pandas as pd

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data_nan.csv')
weather_df.head()

        day  temperature  windspeed   event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0   Sunny
2  1/5/2017         -1.0        NaN    Snow
3  1/6/2017          NaN        7.0     NaN
4  1/7/2017         32.0        NaN    Rain

In [ ]:
weather_df['bfill_temperature'] = weather_df['temperature'].fillna(method = 'bfill')

In [ ]:
weather_df[['day', 'temperature', 'bfill_temperature']]

          day  temperature  bfill_temperature
0    1/1/2017         32.0               32.0
1    1/4/2017          NaN               -1.0
2    1/5/2017         -1.0               -1.0
3    1/6/2017          NaN               32.0
4    1/7/2017         32.0               32.0
5    1/8/2017          NaN               34.0
6    1/9/2017          NaN               34.0
7   1/10/2017         34.0               34.0
8   1/11/2017         -4.0               -4.0
9   1/12/2017         26.0               26.0
10  1/13/2017         12.0               12.0
11  1/11/2017         -1.0               -1.0
12  1/14/2017         40.0               40.0

#### Interpolate(Linear Interpolation)
<li>method = time</li>

In [ ]:
weather_df['interpolate_temp'] = weather_df['temperature'].interpolate(method = 'linear')

In [ ]:
weather_df[['day', 'temperature', 'interpolate_temp']]

          day  temperature  interpolate_temp
0    1/1/2017         32.0         32.000000
1    1/4/2017          NaN         15.500000
2    1/5/2017         -1.0         -1.000000
3    1/6/2017          NaN         15.500000
4    1/7/2017         32.0         32.000000
5    1/8/2017          NaN         32.666667
6    1/9/2017          NaN         33.333333
7   1/10/2017         34.0         34.000000
8   1/11/2017         -4.0         -4.000000
9   1/12/2017         26.0         26.000000
10  1/13/2017         12.0         12.000000
11  1/11/2017         -1.0         -1.000000
12  1/14/2017         40.0         40.000000

In [ ]:
weather_df = pd.read_csv('./csv_data/weather_data_nan.csv', parse_dates = ['day'])
weather_df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0   Rain
1  2017-01-04          NaN        9.0   Sunny
2  2017-01-05         -1.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08          NaN        NaN   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         -4.0        NaN    Snow
9  2017-01-12         26.0       12.0   Sunny
10 2017-01-13         12.0       12.0   Rainy
11 2017-01-11         -1.0       12.0    Snow
12 2017-01-14         40.0        NaN   Sunny

In [ ]:
weather_df.set_index('day', inplace = True)
weather_df.head()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0   Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         -1.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain

In [ ]:
weather_df['interpolate_time'] = weather_df['temperature'].interpolate(method = 'time')

In [ ]:
weather_df.head(10)

            temperature  windspeed   event  interpolate_time
day
2017-01-01         32.0        6.0   Rain          32.000000
2017-01-04          NaN        9.0   Sunny          7.250000
2017-01-05         -1.0        NaN    Snow         -1.000000
2017-01-06          NaN        7.0     NaN         15.500000
2017-01-07         32.0        NaN    Rain         32.000000
2017-01-08          NaN        NaN   Sunny         32.666667
2017-01-09          NaN        NaN     NaN         33.333333
2017-01-10         34.0        8.0  Cloudy         34.000000
2017-01-11         -4.0        NaN    Snow         -4.000000
2017-01-12         26.0       12.0   Sunny         26.000000

#### dropna()
<li>dropna() with how and threshold parameter</li>

In [ ]:
clean_weather_df = weather_df.dropna()

In [ ]:
weather_df[['temperature', 'windspeed']].dropna(how = 'all')

            temperature  windspeed
day
2017-01-01         32.0        6.0
2017-01-04          NaN        9.0
2017-01-05         -1.0        NaN
2017-01-06          NaN        7.0
2017-01-07         32.0        NaN
2017-01-10         34.0        8.0
2017-01-11         -4.0        NaN
2017-01-12         26.0       12.0
2017-01-13         12.0       12.0
2017-01-11         -1.0       12.0
2017-01-14         40.0        NaN

In [ ]:
clean_weather_df

            temperature  windspeed   event  interpolate_time
day
2017-01-01         32.0        6.0   Rain               32.0
2017-01-10         34.0        8.0  Cloudy              34.0
2017-01-12         26.0       12.0   Sunny              26.0
2017-01-13         12.0       12.0   Rainy              12.0
2017-01-11         -1.0       12.0    Snow              -1.0

#### Handle Missing Values using .replace() method

In [ ]:
weather_df.replace('Rainy', 'Rain')

            temperature  windspeed   event  interpolate_time
day
2017-01-01         32.0        6.0   Rain          32.000000
2017-01-04          NaN        9.0   Sunny          7.250000
2017-01-05         -1.0        NaN    Snow         -1.000000
2017-01-06          NaN        7.0     NaN         15.500000
2017-01-07         32.0        NaN    Rain         32.000000
2017-01-08          NaN        NaN   Sunny         32.666667
2017-01-09          NaN        NaN     NaN         33.333333
2017-01-10         34.0        8.0  Cloudy         34.000000
2017-01-11         -4.0        NaN    Snow         -4.000000
2017-01-12         26.0       12.0   Sunny         26.000000
2017-01-13         12.0       12.0    Rain         12.000000
2017-01-11         -1.0       12.0    Snow         -1.000000
2017-01-14         40.0        NaN   Sunny         40.000000

In [ ]:
import numpy as np
weather_df.replace([-4, -1, np.nan], 0)

            temperature  windspeed   event  interpolate_time
day
2017-01-01         32.0        6.0   Rain          32.000000
2017-01-04          0.0        9.0   Sunny          7.250000
2017-01-05          0.0        0.0    Snow          0.000000
2017-01-06          0.0        7.0       0         15.500000
2017-01-07         32.0        0.0    Rain         32.000000
2017-01-08          0.0        0.0   Sunny         32.666667
2017-01-09          0.0        0.0       0         33.333333
2017-01-10         34.0        8.0  Cloudy         34.000000
2017-01-11          0.0        0.0    Snow          0.000000
2017-01-12         26.0       12.0   Sunny         26.000000
2017-01-13         12.0       12.0   Rainy         12.000000
2017-01-11          0.0       12.0    Snow          0.000000
2017-01-14         40.0        0.0   Sunny         40.000000

#### Replacing Values Using a Dictionary (using columns and without using columns)

In [ ]:
weather_df.replace({-1.0 : 0, -4.0 : 0, np.nan: 0})

            temperature  windspeed   event  interpolate_time
day
2017-01-01         32.0        6.0   Rain          32.000000
2017-01-04          0.0        9.0   Sunny          7.250000
2017-01-05          0.0        0.0    Snow          0.000000
2017-01-06          0.0        7.0       0         15.500000
2017-01-07         32.0        0.0    Rain         32.000000
2017-01-08          0.0        0.0   Sunny         32.666667
2017-01-09          0.0        0.0       0         33.333333
2017-01-10         34.0        8.0  Cloudy         34.000000
2017-01-11          0.0        0.0    Snow          0.000000
2017-01-12         26.0       12.0   Sunny         26.000000
2017-01-13         12.0       12.0   Rainy         12.000000
2017-01-11          0.0       12.0    Snow          0.000000
2017-01-14         40.0        0.0   Sunny         40.000000

In [ ]:
weather_df.replace({'temperature': {np.nan: weather_df['temperature'].mean()},
                   'windspeed': {np.nan: weather_df['windspeed'].median()},
                    'event': {np.nan: 'windy'}
                   })

            temperature  windspeed   event  interpolate_time
day
2017-01-01    32.000000        6.0   Rain          32.000000
2017-01-04    18.888889        9.0   Sunny          7.250000
2017-01-05    -1.000000        9.0    Snow         -1.000000
2017-01-06    18.888889        7.0   windy         15.500000
2017-01-07    32.000000        9.0    Rain         32.000000
2017-01-08    18.888889        9.0   Sunny         32.666667
2017-01-09    18.888889        9.0   windy         33.333333
2017-01-10    34.000000        8.0  Cloudy         34.000000
2017-01-11    -4.000000        9.0    Snow         -4.000000
2017-01-12    26.000000       12.0   Sunny         26.000000
2017-01-13    12.000000       12.0   Rainy         12.000000
2017-01-11    -1.000000       12.0    Snow         -1.000000
2017-01-14    40.000000        9.0   Sunny         40.000000

#### Replacing values using a regex
<code>
df.replace(original_value, replaced_value, regex = True)
</code>

In [ ]:
df = pd.read_csv('./csv_data/weather_dataset.csv', parse_dates = ['day'])
df.head()

         day temperature windspeed   event
0 2017-01-01   32Celsius    6.0m/s   Rain
1 2017-01-04         NaN      9m/s   Sunny
2 2017-01-05   -1Celsius       NaN    Snow
3 2017-01-06         NaN      7m/s     NaN
4 2017-01-07   32Celsius       NaN    Rain

In [ ]:
df.set_index('day', inplace = True)

In [ ]:
df.replace("[A-Za-z]","", regex = True)

           temperature windspeed event
day
2017-01-01          32      6.0/
2017-01-04         NaN        9/
2017-01-05          -1       NaN
2017-01-06         NaN        7/   NaN
2017-01-07          32       NaN
2017-01-08         NaN       NaN
2017-01-09         NaN       NaN   NaN
2017-01-10          34      8.0/
2017-01-11          -4       NaN
2017-01-12        26.0      12.0
2017-01-13        12.0      12.0
2017-01-11        -1.0      12.0
2017-01-14        40.0       NaN

In [ ]:
df['temperature'].replace("[A-Za-z]", "", regex = True, inplace = True)

In [ ]:
df['windspeed'].replace("[A-Za-z]", "", regex = True, inplace = True)

In [ ]:
df.head()

           temperature windspeed   event
day
2017-01-01          32      6.0/   Rain
2017-01-04         NaN        9/   Sunny
2017-01-05          -1       NaN    Snow
2017-01-06         NaN        7/     NaN
2017-01-07          32       NaN    Rain

In [ ]:
new_df = pd.read_csv('./csv_data/weather_dataset.csv')
new_df.head()

        day temperature windspeed   event
0  1/1/2017   32Celsius    6.0m/s   Rain
1  1/4/2017         NaN      9m/s   Sunny
2  1/5/2017   -1Celsius       NaN    Snow
3  1/6/2017         NaN      7m/s     NaN
4  1/7/2017   32Celsius       NaN    Rain

In [ ]:
new_df['windspeed'].replace("[a-z/a-z]", "", regex = True, inplace = True)

In [ ]:
new_df.head()

        day temperature windspeed   event
0  1/1/2017   32Celsius       6.0   Rain
1  1/4/2017         NaN         9   Sunny
2  1/5/2017   -1Celsius       NaN    Snow
3  1/6/2017         NaN         7     NaN
4  1/7/2017   32Celsius       NaN    Rain

In [ ]:
new_df['event'] = new_df['event'].str.strip()

In [ ]:
new_df.replace({'event': {np.nan: 'Windy', 'Rain': 'Rainy',
                         'Snow': 'Snowy'}}, inplace = True)
new_df

          day temperature windspeed   event
0    1/1/2017   32Celsius       6.0   Rainy
1    1/4/2017         NaN         9   Sunny
2    1/5/2017   -1Celsius       NaN   Snowy
3    1/6/2017         NaN         7   Windy
4    1/7/2017   32Celsius       NaN   Rainy
5    1/8/2017         NaN       NaN   Sunny
6    1/9/2017         NaN       NaN   Windy
7   1/10/2017         34C       8.0  Cloudy
8   1/11/2017         -4K       NaN   Snowy
9   1/12/2017        26.0      12.0   Sunny
10  1/13/2017        12.0      12.0   Rainy
11  1/11/2017        -1.0      12.0   Snowy
12  1/14/2017        40.0       NaN   Sunny

In [ ]:
new_df['playing'] = 0

In [ ]:
new_df.loc[(new_df['event'] == "Sunny") |
          (new_df['event'] == "Windy"), 'playing'] = 1

In [ ]:
new_df

          day temperature windspeed   event  playing
0    1/1/2017   32Celsius       6.0   Rainy        0
1    1/4/2017         NaN         9   Sunny        1
2    1/5/2017   -1Celsius       NaN   Snowy        0
3    1/6/2017         NaN         7   Windy        1
4    1/7/2017   32Celsius       NaN   Rainy        0
5    1/8/2017         NaN       NaN   Sunny        1
6    1/9/2017         NaN       NaN   Windy        1
7   1/10/2017         34C       8.0  Cloudy        0
8   1/11/2017         -4K       NaN   Snowy        0
9   1/12/2017        26.0      12.0   Sunny        1
10  1/13/2017        12.0      12.0   Rainy        0
11  1/11/2017        -1.0      12.0   Snowy        0
12  1/14/2017        40.0       NaN   Sunny        1

#### Mapping values of a particular column using replace method
<li>Replacing the list of values using another list of values</li>
<li>Replacing values of a particular column using a dictionary</li>

In [ ]:
new_df.replace([0, 1], ['No', 'Yes'], inplace = True)

In [ ]:
new_df.head()

        day temperature windspeed  event playing
0  1/1/2017   32Celsius       6.0  Rainy      No
1  1/4/2017         NaN         9  Sunny     Yes
2  1/5/2017   -1Celsius       NaN  Snowy      No
3  1/6/2017         NaN         7  Windy     Yes
4  1/7/2017   32Celsius       NaN  Rainy      No

#### GroupBy Functions
<li>Pandas groupby is used for grouping the data according to the categories and apply a function to the categories.</li>
<li>It also helps to aggregate data efficiently.</li>
<li>Pandas dataframe.groupby() function is used to split the data into groups based on some criteria.</li>
<code>
    df.groupby(col_name, as_index, sort, dropna)
</code>
<li>It uses split, apply, combine principle to create a groupby dataframe.</li>
<li>The groupby function accepts multiple parameters. Some of them are as follows:</li>
<ol>
    <li>col_name(required): the name of column against which you want to group elements.</li>
    <li>as_index(optional): default = True, if you want to include groupby column as an index set it        to True else False.</li>
    <li>sort(optional): default = True, if you want to sort the group based on keys then keep it as       True else False.</li>
    <li>dropna(optional): default = True, if you keep it as false then it will also include Nan values     as a separate group.</li>
</ol>

In [ ]:
import pandas as pd
df = pd.read_csv('weather_data_nan.csv')
df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        9.0  Sunny
2  1/5/2017         -1.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

In [ ]:
df['event'] = df['event'].str.strip()

In [ ]:
df.groupby('event')['temperature'].mean().to_frame()

        temperature
event
Cloudy         34.0
Rain           32.0
Rainy          12.0
Snow           -2.0
Sunny          33.0

In [ ]:
df.groupby('event', sort = False)['windspeed'].mean().to_frame()

        windspeed
event
Rain          6.0
Sunny        10.5
Snow         12.0
Cloudy        8.0
Rainy        12.0

In [ ]:
df.groupby('event', sort = True)[['windspeed', 'temperature']].mean()

        windspeed  temperature
event
Cloudy        8.0         34.0
Rain          6.0         32.0
Rainy        12.0         12.0
Snow         12.0         -2.0
Sunny        10.5         33.0

In [ ]:
df.groupby('event', sort = True, dropna = False)[['windspeed', 'temperature']].mean()

        windspeed  temperature
event
Cloudy        8.0         34.0
Rain          6.0         32.0
Rainy        12.0         12.0
Snow         12.0         -2.0
Sunny        10.5         33.0
NaN           7.0          NaN

In [ ]:
df.groupby('event', sort = True, as_index = False)[['windspeed', 'temperature']].mean()

    event  windspeed  temperature
0  Cloudy        8.0         34.0
1    Rain        6.0         32.0
2   Rainy       12.0         12.0
3    Snow       12.0         -2.0
4   Sunny       10.5         33.0

### GroupBy Aggregation Functions
<li>Here are some of the aggregating functions available in Pandas and quick summary of what it does.</li>
<ol>
    <li>mean(): Compute mean of groups for numeric columns</li>
    <li>sum(): Compute sum of group values for numeric columns</li>
    <li>size(): Compute group sizes</li>
    <li>count(): Compute count of group</li>
    <li>std(): Standard deviation of groups for numeric columns</li>
    <li>var(): Compute variance of groups for numeric columns</li>
    <li>describe(): Generates descriptive statistics</li>
    <li>first(): Compute first of group values</li>
    <li>last(): Compute last of group values</li>
    <li>nth() : Take nth value, or a subset if n is a list</li>
    <li>min(): Compute min of group values</li>
    <li>max(): Compute max of group values</li>
</ol>

In [ ]:
car_df = pd.read_csv('./csv_data/car_details.csv')
car_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
car_df['brand'] = car_df['name'].str.strip().str.split(' ').str[0]

In [ ]:
car_df.groupby(['year','brand'], as_index = False)['km_driven'].mean()

     year       brand      km_driven
0    1992      Maruti  100000.000000
1    1995      Maruti  100000.000000
2    1996    Mahindra   47500.000000
3    1997    Mahindra  120000.000000
4    1997      Maruti   75000.000000
..    ...         ...            ...
283  2020    Mahindra   20333.333333
284  2020      Maruti   24223.076923
285  2020     Renault   10500.000000
286  2020        Tata    5333.333333
287  2020  Volkswagen    5000.000000

[288 rows x 3 columns]

In [ ]:
car_df.groupby(['year','brand'], as_index = False)['selling_price'].sum()

     year       brand  selling_price
0    1992      Maruti          50000
1    1995      Maruti          95000
2    1996    Mahindra         450000
3    1997    Mahindra         150000
4    1997      Maruti         129000
..    ...         ...            ...
283  2020    Mahindra        4000000
284  2020      Maruti        5522000
285  2020     Renault         841000
286  2020        Tata        1756000
287  2020  Volkswagen         802000

[288 rows x 3 columns]

In [ ]:
car_df.groupby(['year','brand'], as_index = False)['selling_price'].count()

     year       brand  selling_price
0    1992      Maruti              1
1    1995      Maruti              1
2    1996    Mahindra              2
3    1997    Mahindra              1
4    1997      Maruti              2
..    ...         ...            ...
283  2020    Mahindra              3
284  2020      Maruti             13
285  2020     Renault              2
286  2020        Tata              3
287  2020  Volkswagen              1

[288 rows x 3 columns]

In [ ]:
car_df.groupby(['year','brand'], as_index = False)['selling_price'].size()

     year       brand  size
0    1992      Maruti     1
1    1995      Maruti     1
2    1996    Mahindra     2
3    1997    Mahindra     1
4    1997      Maruti     2
..    ...         ...   ...
283  2020    Mahindra     3
284  2020      Maruti    13
285  2020     Renault     2
286  2020        Tata     3
287  2020  Volkswagen     1

[288 rows x 3 columns]

In [ ]:
car_df.groupby(['brand'], as_index = False).nth(2)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
5,Maruti Alto LX BSIII,2007,140000,125000,Petrol,Individual,Manual,First Owner,Maruti
8,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner,Hyundai
20,Tata Indigo Grand Petrol,2014,240000,60000,Petrol,Individual,Manual,Second Owner,Tata
28,Chevrolet Enjoy TCDi LTZ 7 Seater,2013,390000,33000,Diesel,Individual,Manual,Second Owner,Chevrolet
33,Honda City V MT,2018,930000,14500,Petrol,Dealer,Manual,First Owner,Honda
38,Toyota Corolla Altis G AT,2016,900000,50000,Petrol,Individual,Automatic,First Owner,Toyota
41,Mercedes-Benz E-Class E 200 CGI Elegance,2010,850000,119000,Petrol,Dealer,Automatic,First Owner,Mercedes-Benz
44,Audi Q7 35 TDI Quattro Premium,2009,1250000,78000,Diesel,Dealer,Automatic,Third Owner,Audi
61,Mahindra Jeep CL 500 MDI,1996,250000,35000,Diesel,Individual,Manual,Second Owner,Mahindra
97,Datsun RediGO 1.0 S,2017,210000,15000,Petrol,Dealer,Manual,Second Owner,Datsun
105,BMW 7 Series 730Ld,2012,2500000,48000,Diesel,Dealer,Automatic,First Owner,BMW
115,Renault KWID RXT,2017,350000,25000,Petrol,Individual,Manual,First Owner,Renault
135,Ford EcoSport 1.5 Diesel Titanium Plus BSIV,2017,840000,49213,Diesel,Dealer,Manual,First Owner,Ford
180,Skoda Rapid 1.6 MPI Ambition With Alloy Wheel,2015,640000,23000,Petrol,Individual,Manual,First Owner,Skoda
203,Nissan Micra XL,2014,210000,40000,Petrol,Individual,Manual,Second Owner,Nissan
220,Volkswagen Ameo 1.5 TDI Highline,2017,640000,56000,Diesel,Dealer,Manual,First Owner,Volkswagen
497,Fiat Avventura Urban Cross 1.3 Multijet Emotion,2018,650000,38083,Diesel,Dealer,Manual,First Owner,Fiat
536,Jaguar XF 5.0 Litre V8 Petrol,2012,2050000,66363,Petrol,Dealer,Automatic,Second Owner,Jaguar
1088,Land Rover Discovery Sport SD4 HSE Luxury,2016,3500000,53000,Diesel,Dealer,Automatic,First Owner,Land
1864,Mitsubishi Pajero 2.8 SFX BSIV Dual Tone,2011,825000,120000,Diesel,Individual,Manual,First Owner,Mitsubishi
3320,Volvo XC60 D3 Kinetic,2012,1750000,115992,Diesel,Dealer,Automatic,Third Owner,Volvo
3790,Jeep Compass 2.0 Longitude Option BSIV,2017,1490000,22038,Diesel,Individual,Manual,First Owner,Jeep
3912,Ambassador CLASSIC 1500 DSL AC,2005,120000,50000,Diesel,Individual,Manual,Second Owner,Ambassador

#### Question
<li>Read 'car_details.csv' file and create a pandas dataframe from this file.</li>
<li>Find the maximum price for each of the car brand.</li>
<li>Find the average price for each of the fuel types.</li>
<li>Find the average km_driven for each of the seller_types.</li>
<li>Find the count of each of the car names.</li>
<li>Find the maximum km_driven for each of the owner types.</li>

In [ ]:
car_df.groupby('brand')['selling_price'].max().to_frame()

               selling_price
brand
Ambassador            430000
Audi                 8900000
BMW                  4950000
Chevrolet            1000000
Daewoo                 60000
Datsun                450000
Fiat                  890000
Force                 346000
Ford                 3200000
Honda                1800000
Hyundai              1650000
Isuzu                1500000
Jaguar               2550000
Jeep                 1700000
Kia                  1300000
Land                 4200000
MG                   1860000
Mahindra             2700000
Maruti               1100000
Mercedes-Benz        8150000
Mitsubishi           1090000
Nissan               1350000
OpelCorsa             142000
Renault              1000000
Skoda                1200000
Tata                 1700000
Toyota               3200000
Volkswagen           1350000
Volvo                4500000

In [ ]:
car_df.groupby(['fuel'], as_index = False)['selling_price'].mean()

       fuel  selling_price
0       CNG  277174.925000
1    Diesel  669094.252206
2  Electric  310000.000000
3       LPG  167826.043478
4    Petrol  344840.137541

In [ ]:
car_df.groupby(['seller_type'], as_index = False)['km_driven'].mean()

        seller_type     km_driven
0            Dealer  52827.259557
1        Individual  71167.556104
2  Trustmark Dealer  39202.215686

In [ ]:
car_df.groupby(['brand'], as_index = False)['name'].count()

            brand  name
0      Ambassador     4
1            Audi    60
2             BMW    39
3       Chevrolet   188
4          Daewoo     1
5          Datsun    37
6            Fiat    37
7           Force     1
8            Ford   238
9           Honda   252
10        Hyundai   821
11          Isuzu     1
12         Jaguar     6
13           Jeep     3
14            Kia     1
15           Land     5
16             MG     2
17       Mahindra   365
18         Maruti  1280
19  Mercedes-Benz    35
20     Mitsubishi     6
21         Nissan    64
22      OpelCorsa     2
23        Renault   146
24          Skoda    68
25           Tata   361
26         Toyota   206
27     Volkswagen   107
28          Volvo     4

In [ ]:
car_df.groupby(['owner'], as_index = False)['km_driven'].max()

                  owner  km_driven
0           First Owner     806599
1  Fourth & Above Owner     245244
2          Second Owner     350000
3        Test Drive Car      24585
4           Third Owner     400000

####  Concatenating DataFrames
<li>pandas.concat() function does all the heavy lifting of performing concatenation operations along with an axis</li>
<li>If we want to join two individual dataframes and create a combined dataframe out of it, we can use concatenation operation for doing so.</li>
<li>We can use concatenation operation along the rows(axis=0) as well as along the columns(axis = 1)</li>

**syntax**

<code>
    pd.concat([df1,df2], axis, keys, ignore_index)
</code>

<li>df1 and df2 (required) are two dataframes which we want to merge.</li>
<li>axis: axis to concatenate along, (possible values; 0(along the rows) and 1 (along the cols) default = 0 (along the rows).</li>
<li>keys: sequence to add an identifier to the result indexes; default = None</li>
<li>ignore_index: if True, do not use the index values along the concatenation axis; default = False</li>

#### Concatenating Dataframes along the rows
![](images/concat_rows.png)

In [ ]:
df1 = pd.DataFrame({"Name": ["Prabhat", "Hari", "Shyam", "Sita", "Mahima"],
                   "Age": [24, 34, 50, 32, 18],
                   "Address": ["Manigram", "Dhanewa", "Bardaghat", "Manglapur", "Bharatpur"]
                   })
df1.head()

      Name  Age    Address
0  Prabhat   24   Manigram
1     Hari   34    Dhanewa
2    Shyam   50  Bardaghat
3     Sita   32  Manglapur
4   Mahima   18  Bharatpur

In [ ]:
df2 = pd.DataFrame({"Name": ["Sunil", "Bhawana", "Shiva", "Himal", "Dipen"],
                   "Age": [23, 22, 23, 25, 26],
                   "Address": ["Kathmandu", "Ramechap", "Kalangki",
                               "Chaupatta", "Kirtipur"]
                   })
df2.head()

      Name  Age    Address
0    Sunil   23  Kathmandu
1  Bhawana   22   Ramechap
2    Shiva   23   Kalangki
3    Himal   25  Chaupatta
4    Dipen   26   Kirtipur

In [ ]:
combined_df1 = pd.concat([df1, df2], axis = 0, ignore_index = True)
combined_df1

      Name  Age    Address
0  Prabhat   24   Manigram
1     Hari   34    Dhanewa
2    Shyam   50  Bardaghat
3     Sita   32  Manglapur
4   Mahima   18  Bharatpur
5    Sunil   23  Kathmandu
6  Bhawana   22   Ramechap
7    Shiva   23   Kalangki
8    Himal   25  Chaupatta
9    Dipen   26   Kirtipur

#### Concatenating DataFrames along columns
![](images/concat_cols.png)

In [ ]:
df3 = pd.DataFrame({"Gender": ["Male", "Male", "Male", "Female", "Female",
                              "Male", "Female", "Male", "Male", "Male"],
                   "Height": [1.6, 1.7, 1.5, 1.6, 1.65, 1.72, 1.43, 1.8, 1.71, 1.42],
                   "Weight": [70, 67, 65, 45, 48, 73, 55, 82, 67, 55]})
df3.head()

   Gender  Height  Weight
0    Male    1.60      70
1    Male    1.70      67
2    Male    1.50      65
3  Female    1.60      45
4  Female    1.65      48

In [ ]:
combined_df2 = pd.concat([combined_df1, df3], axis = 1)
combined_df2.head()

      Name  Age    Address  Gender  Height  Weight
0  Prabhat   24   Manigram    Male    1.60      70
1     Hari   34    Dhanewa    Male    1.70      67
2    Shyam   50  Bardaghat    Male    1.50      65
3     Sita   32  Manglapur  Female    1.60      45
4   Mahima   18  Bharatpur  Female    1.65      48

#### Merge
<li>Pandas has full-featured, high performance in-memory join operations idiomatically very similar to relational databases like SQL.</li>
<li>Pandas provides a single function, merge, as the entry point for all standard database join operations between DataFrame objects.</li>
<li>The <b>merge()</b> method updates the content of two DataFrame by merging them together, using the specified method(s).</li>
<li>We can use the parameters to control which values to keep and which to replace during merge operation.</li>
<li>We can specify any type of join we want by using how parameter in merge method.</li>
<li>There are four types of join operations. They are :</li>
<ol>
    <b><li>Inner join</li></b>
    <b><li>Left join</li></b>
    <b><li>Right join</li></b>
    <b><li>Outer join</li></b>
</ol>

#### 1. Inner Join
![](images/inner_join.png)

In [ ]:
df1 = pd.DataFrame({"name": ["Prabhat", "Hari", "Shyam", "Sita", "Mahima", "Sunil"],
                   "gender": ["Male", "Male", "Male", "Female", "Female", "Male"],
                   "address": ["Manigram", "Dhanewa", "Bardaghat", "Manglapur",
                              "Bharatpur", "Kathmandu"]})
df1.head()

      name  gender    address
0  Prabhat    Male   Manigram
1     Hari    Male    Dhanewa
2    Shyam    Male  Bardaghat
3     Sita  Female  Manglapur
4   Mahima  Female  Bharatpur

In [ ]:
df2 = pd.DataFrame({"name": ["Prabhat", "Hari", "Shiva", "Bhawana", "Mahima", "Sunil"],
                   "age": [24, 34, 50, 32, 18, 23],
                   "height": [1.6, 1.7, 1.8, 1.43, 1.65, 1.73]})

df2.head()

      name  age  height
0  Prabhat   24    1.60
1     Hari   34    1.70
2    Shiva   50    1.80
3  Bhawana   32    1.43
4   Mahima   18    1.65

In [ ]:
inner_df = pd.merge(df1, df2, on = "name", how = "inner")
inner_df.head(10)

      name  gender    address  age  height
0  Prabhat    Male   Manigram   24    1.60
1     Hari    Male    Dhanewa   34    1.70
2   Mahima  Female  Bharatpur   18    1.65
3    Sunil    Male  Kathmandu   23    1.73

#### 2. Left Join

![](images/left_join.png)

In [ ]:
left_df = pd.merge(df1, df2, how = "left", on = "name")
left_df

      name  gender    address   age  height
0  Prabhat    Male   Manigram  24.0    1.60
1     Hari    Male    Dhanewa  34.0    1.70
2    Shyam    Male  Bardaghat   NaN     NaN
3     Sita  Female  Manglapur   NaN     NaN
4   Mahima  Female  Bharatpur  18.0    1.65
5    Sunil    Male  Kathmandu  23.0    1.73

#### 3. Right Join

![](images/right_join.png)

In [ ]:
right_df = pd.merge(df1, df2, how = "right", on = "name")
right_df

      name  gender    address  age  height
0  Prabhat    Male   Manigram   24    1.60
1     Hari    Male    Dhanewa   34    1.70
2    Shiva     NaN        NaN   50    1.80
3  Bhawana     NaN        NaN   32    1.43
4   Mahima  Female  Bharatpur   18    1.65
5    Sunil    Male  Kathmandu   23    1.73

#### 4. Outer Join

![](images/outer_join.png)

In [ ]:
outer_df = pd.merge(df1, df2, how = "outer", on = "name")
outer_df

      name  gender    address   age  height
0  Prabhat    Male   Manigram  24.0    1.60
1     Hari    Male    Dhanewa  34.0    1.70
2    Shyam    Male  Bardaghat   NaN     NaN
3     Sita  Female  Manglapur   NaN     NaN
4   Mahima  Female  Bharatpur  18.0    1.65
5    Sunil    Male  Kathmandu  23.0    1.73
6    Shiva     NaN        NaN  50.0    1.80
7  Bhawana     NaN        NaN  32.0    1.43

#### Crosstab

<li>Cross tabulation is used to quantitatively analyze the relationship between multiple variables.</li>
<li>Cross tabulations — also referred to as contingency tables or crosstabs.</li>
<li>They group variables together and enable researchers to understand the correlation between different variables.<li>
<li>When we are doing multivariate analysis then we often came across crosstab() methods in pandas.</li>

**Syntax**

<code>
    pd.crosstab(index, columns, values, margins, margin_names, normalize,aggfunc, dropna)
</code>
<ol>
    <li>index : array-like, Series, or list of arrays/Series, Values to group by in the rows.</li>
    <li>columns : array-like, Series, or list of arrays/Series, Values to group by in the columns.</li>
    <li>values : array-like, optional, array of values to aggregate according to the factors. Requires `aggfunc` be specified.     </li>
    <li>aggfunc : function, optional, If specified, requires `values` be specified as well.</li>
    <li>margins : bool, default False, Add row/column margins (subtotals).</li>
    <li>margins_name : str, default ‘All’, Name of the row/column that will contain the totals when margins is True.</li>
    <li>dropna : bool, default True, Do not include columns whose entries are all NaN.</li>
    <li>normalize: </li>
    <ol>
        <li>If passed ‘all’ or True, will normalize over all values.</li>
        <li>If passed ‘index’ will normalize over each row.</li>
        <li>If passed ‘columns’ will normalize over each column.</li>
        <li>If margins is True, will also normalize margin values.</li>
    </ol>
</ol>

In [ ]:
import pandas as pd

In [ ]:
car_df = pd.read_csv('csv_data/car_details.csv')
car_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
car_df.dtypes

name             object
year              int64
selling_price     int64
km_driven         int64
fuel             object
seller_type      object
transmission     object
owner            object
dtype: object

In [ ]:
car_df['price_range'] = "Cheap"

In [ ]:
car_df.loc[((car_df['selling_price'] > 50000) &
           (car_df['selling_price'] < 100000)), 'price_range'] = "Medium"

car_df.loc[((car_df['selling_price'] > 100000) &
           (car_df['selling_price'] < 500000)), 'price_range'] = "Expensive"

car_df.loc[car_df['selling_price'] > 500000, 'price_range'] = "Very Expensive"

In [ ]:
car_df['price_range'].value_counts()

Expensive         2400
Very Expensive    1461
Medium             282
Cheap              197
Name: price_range, dtype: int64

In [ ]:
pd.crosstab(car_df['price_range'], car_df['fuel'])

fuel            CNG  Diesel  Electric  LPG  Petrol
price_range
Cheap             1      70         0    2     124
Expensive        33    1024         1   16    1326
Medium            2      31         0    5     244
Very Expensive    4    1028         0    0     429

In [ ]:
pd.crosstab(car_df['price_range'], car_df['fuel'], margins = True,
           margins_name = "Total")

fuel            CNG  Diesel  Electric  LPG  Petrol  Total
price_range
Cheap             1      70         0    2     124    197
Expensive        33    1024         1   16    1326   2400
Medium            2      31         0    5     244    282
Very Expensive    4    1028         0    0     429   1461
Total            40    2153         1   23    2123   4340

In [ ]:
pd.crosstab(car_df['price_range'], car_df['fuel'], margins = True,
            normalize = 'index')

fuel                 CNG    Diesel  Electric       LPG    Petrol
price_range
Cheap           0.005076  0.355330  0.000000  0.010152  0.629442
Expensive       0.013750  0.426667  0.000417  0.006667  0.552500
Medium          0.007092  0.109929  0.000000  0.017730  0.865248
Very Expensive  0.002738  0.703628  0.000000  0.000000  0.293634
All             0.009217  0.496083  0.000230  0.005300  0.489171

In [ ]:
pd.crosstab(car_df['price_range'], car_df['fuel'], margins = True,
            normalize = 'columns')

fuel              CNG    Diesel  Electric       LPG    Petrol       All
price_range
Cheap           0.025  0.032513       0.0  0.086957  0.058408  0.045392
Expensive       0.825  0.475615       1.0  0.695652  0.624588  0.552995
Medium          0.050  0.014399       0.0  0.217391  0.114932  0.064977
Very Expensive  0.100  0.477473       0.0  0.000000  0.202073  0.336636

In [ ]:
pd.crosstab(car_df['price_range'], car_df['fuel'], margins = True,
            normalize = 'all')

fuel                 CNG    Diesel  Electric       LPG    Petrol       All
price_range
Cheap           0.000230  0.016129   0.00000  0.000461  0.028571  0.045392
Expensive       0.007604  0.235945   0.00023  0.003687  0.305530  0.552995
Medium          0.000461  0.007143   0.00000  0.001152  0.056221  0.064977
Very Expensive  0.000922  0.236866   0.00000  0.000000  0.098848  0.336636
All             0.009217  0.496083   0.00023  0.005300  0.489171  1.000000

#### Pivot
<li>pivot() method produces pivot table based on 3 columns of the DataFrame. Uses unique values from index / columns and fills with values.</li>

    
**syntax**
<code>
pd.pivot(index, columns, values)
</code>
    
<b>Parameters:</b>
<ol>
    <li>index[ndarray] : Labels to use to make new frame’s index</li>
    <li>columns[ndarray] : Labels to use to make new frame’s columns</li>
    <li>values[ndarray] : Values to use for populating new frame’s values</li>
</ol>

**Returns: Reshaped DataFrame**

**Exception: ValueError raised if there are any duplicates.**

In [ ]:
car_df['brand'] = car_df['name'].str.strip().str.split(' ').str[0].str.strip()

In [ ]:
car_df['brand'].value_counts()

Maruti           1280
Hyundai           821
Mahindra          365
Tata              361
Honda             252
Ford              238
Toyota            206
Chevrolet         188
Renault           146
Volkswagen        107
Skoda              68
Nissan             64
Audi               60
BMW                39
Fiat               37
Datsun             37
Mercedes-Benz      35
Jaguar              6
Mitsubishi          6
Land                5
Volvo               4
Ambassador          4
Jeep                3
MG                  2
OpelCorsa           2
Daewoo              1
Force               1
Isuzu               1
Kia                 1
Name: brand, dtype: int64

In [ ]:
pd.pivot_table(data = car_df, index = 'price_range', columns = 'brand',
         values = 'selling_price')

brand,Ambassador,Audi,BMW,Chevrolet,Daewoo,Datsun,Fiat,Force,Ford,Honda,...,Mercedes-Benz,Mitsubishi,Nissan,OpelCorsa,Renault,Skoda,Tata,Toyota,Volkswagen,Volvo
price_range,,,,,,,,,,,,,,,,,,,,,
Cheap,50000.000000,NaN,NaN,387500.000000,NaN,NaN,500000.000000,NaN,274000.000000,450000.000000,...,NaN,NaN,500000.000000,35000.0,500000.000000,500000.000000,149310.344828,5.000000e+05,500000.000000,NaN
Expensive,223333.333333,NaN,4.800000e+05,223131.712575,NaN,297026.945946,246999.965517,346000.0,270392.476636,333456.629921,...,3.500000e+05,NaN,314128.153846,142000.0,347234.216216,336139.534884,235267.504386,3.505555e+05,332859.126761,NaN
Medium,NaN,NaN,NaN,81062.909091,60000.0,NaN,78000.000000,NaN,75600.000000,75000.000000,...,NaN,NaN,NaN,NaN,NaN,90000.000000,75432.948276,9.500000e+04,NaN,NaN
Very Expensive,NaN,1.931633e+06,3.010263e+06,800000.000000,NaN,NaN,696666.666667,NaN,885262.677966,778382.582609,...,2.848029e+06,840000.0,692619.000000,NaN,662062.468750,794652.173913,874086.847826,1.295024e+06,757882.294118,2556250.0

In [ ]:
car_df.loc[(car_df['brand'] == "Volkswagen") &
          (car_df['price_range'] == "Medium")]

Empty DataFrame
Columns: [name, year, selling_price, km_driven, fuel, seller_type, transmission, owner, price_range, brand]
Index: []

In [ ]:
pd.pivot_table(data = car_df, index = 'seller_type',
              columns = 'owner', values = "selling_price")

owner,First Owner,Fourth & Above Owner,Second Owner,Test Drive Car,Third Owner
seller_type,,,,,
Dealer,754822.233412,117499.500000,490188.467213,954293.941176,462333.222222
Individual,512245.996296,175329.088608,323816.888776,NaN,263590.162712
Trustmark Dealer,919642.857143,NaN,800000.000000,NaN,NaN

In [ ]:
car_df['selling_price'].isnull().sum()

0